import { describe, expect, it } from "vitest";
import { appendActivityInputSchema } from "@workmesh/contracts";
import {
  retentionSoakActivityPayload,
  retentionSoakPreflight,
  retentionSoakReport,
  type RetentionSoakSample,
  type RetentionSoakThresholds,
} from "./retention-soak.js";

const safe = {
  WORKMESH_RETENTION_SOAK: "1",
  WORKMESH_RETENTION_SOAK_DRY_RUN: "1",
  RUN_INTEGRATION: "1",
  DATABASE_URL:
    "postgres://user:password@localhost:5432/workmesh_test_retention",
  REDIS_URL: "redis://localhost:6379",
  WORKMESH_EVENT_PRUNE_ENABLED: "false",
  WORKMESH_RETENTION_CLEANUP_ENABLED: "false",
  WORKMESH_RETENTION_ARCHIVE_ENABLED: "true",
  WORKMESH_RETENTION_SOAK_API_URL: "http://127.0.0.1:3001",
  WORKMESH_RETENTION_SOAK_SESSION_ID: "00000000-0000-4000-8000-000000000001",
  WORKMESH_RETENTION_SOAK_SESSION_TOKEN: "test-token",
  WORKMESH_RETENTION_SOAK_CONTAINERS: "workmesh-api,workmesh-worker",
};

const thresholds: RetentionSoakThresholds = {
  maximumArchiveBacklog: 5,
  maximumArchiveLatencyMs: 300_000,
  maximumOutboxPending: 5,
  maximumOutboxLagMs: 60_000,
  maximumCpuPercent: 85,
  maximumMemoryBytes: 1_073_741_824,
  maximumDatabaseConnections: 50,
  maximumRedisConnections: 50,
  maximumHeartbeatLatencyMs: 1_000,
  maximumActivityLatencyMs: 2_000,
  maximumDatabaseRowsSlopePerHour: 24,
  maximumDatabaseBytesSlopePerHour: 16_777_216,
  maximumTableBytesSlopePerHour: 8_388_608,
  maximumDeadTuplesSlopePerHour: 100,
  maximumRedisLengthSlopePerHour: 24,
  maximumContainerMemorySlopeBytesPerHour: 16_777_216,
};

const sample = (
  overrides: Partial<RetentionSoakSample> = {},
): RetentionSoakSample => ({
  sampledAt: "2026-07-28T00:00:00.000Z",
  floor: "0",
  workerMode: "archive_only",
  workerFresh: true,
  archive: {
    planned: 0,
    uploaded: 0,
    verified: 1,
    verifiedRows: 1,
    failed: 0,
    pruned: 0,
    backlog: 0,
    maximumLatencyMs: 100,
    currentRunGenerated: 0,
    currentRunArchived: 0,
  },
  outbox: { pending: 0, maximumLagMs: 0 },
  redis: { length: 10, connections: 2 },
  database: {
    rows: 100,
    sizeBytes: 1_000,
    tableSizeBytes: 500,
    deadTuples: 0,
    connections: 3,
  },
  workload: {
    heartbeats: 1,
    activities: 1,
    heartbeatLatencyMs: 10,
    activityLatencyMs: 20,
  },
  containers: {
    "workmesh-api": { cpuPercent: 1, memoryBytes: 10_000 },
  },
  ...overrides,
});

describe("retention soak harness", () => {
  it("uses a contract-valid durable activity pulse", () => {
    expect(appendActivityInputSchema.safeParse(
      retentionSoakActivityPayload,
    ).success).toBe(true);
    expect(retentionSoakActivityPayload).toMatchObject({
      kind: "status",
      visibility: "team",
      ephemeral: false,
    });
  });

  it("requires a formal 24-hour archive-only isolated workload", () => {
    expect(retentionSoakPreflight(safe)).toMatchObject({
      durationMs: 86_400_000,
      sampleIntervalMs: 60_000,
      dryRun: true,
      thresholds,
    });
    expect(() =>
      retentionSoakPreflight({
        ...safe,
        DATABASE_URL: "postgres://user:password@localhost:5432/workmesh",
      }),
    ).toThrow("RETENTION_SOAK_REQUIRES_ISOLATED_TEST_DATABASE");
    expect(() =>
      retentionSoakPreflight({
        ...safe,
        WORKMESH_RETENTION_CLEANUP_ENABLED: "true",
      }),
    ).toThrow("RETENTION_SOAK_REQUIRES_CLEANUP_DISABLED");
    expect(() =>
      retentionSoakPreflight({
        ...safe,
        WORKMESH_RETENTION_SOAK_HOURS: "1",
      }),
    ).toThrow("RETENTION_SOAK_FORMAL_DURATION_MUST_BE_24_HOURS");
  });

  it("passes only when events generated by this run are archived and queues converge", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const baseline = sample({
      workload: {
        heartbeats: 0,
        activities: 0,
        heartbeatLatencyMs: 0,
        activityLatencyMs: null,
      },
    });
    const finalSample = sample({
      sampledAt: end.toISOString(),
      archive: {
        planned: 0,
        uploaded: 0,
        verified: 2,
        verifiedRows: 2,
        failed: 0,
        pruned: 0,
        backlog: 0,
        maximumLatencyMs: 100,
        currentRunGenerated: 1,
        currentRunArchived: 1,
      },
      database: {
        rows: 101,
        sizeBytes: 2_000,
        tableSizeBytes: 1_000,
        deadTuples: 0,
        connections: 3,
      },
      workload: {
        heartbeats: 1_440,
        activities: 1,
        heartbeatLatencyMs: 10,
        activityLatencyMs: 20,
      },
    });
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [finalSample],
        100,
        thresholds,
        1,
        ["101"],
      ),
    ).toMatchObject({
      status: "passed",
      retentionFloorAdvanced: false,
      checks: {
        archivesVerifiedThisRun: true,
        generatedEventsArchived: true,
        generatedCursorEvidenceComplete: true,
        archiveBacklogConverged: true,
        outboxConverged: true,
      },
      actual: {
        generatedCursors: ["101"],
        deltas: {
          verifiedSegments: 1,
          verifiedRows: 1,
          databaseRows: 1,
          currentRunGenerated: 1,
          currentRunArchived: 1,
        },
      },
    });
  });

  it("rejects a historical verified segment and zero current-run archive delta", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const baseline = sample();
    const finalSample = sample({
      sampledAt: end.toISOString(),
      archive: {
        ...baseline.archive,
        currentRunGenerated: 1,
        currentRunArchived: 0,
      },
      database: { ...baseline.database, rows: 101 },
    });
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [finalSample],
        100,
        thresholds,
        1,
        ["101"],
      ),
    ).toMatchObject({
      status: "failed",
      checks: {
        archivesVerifiedThisRun: false,
        generatedEventsArchived: false,
        verifiedRowAccounting: false,
      },
    });
  });

  it("rejects aggregate-only archive evidence without exact generated cursors", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const baseline = sample();
    const finalSample = sample({
      sampledAt: end.toISOString(),
      archive: {
        ...baseline.archive,
        verified: 2,
        verifiedRows: 2,
        currentRunGenerated: 1,
        currentRunArchived: 1,
      },
      database: { ...baseline.database, rows: 101 },
    });
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [finalSample],
        100,
        thresholds,
        1,
      ),
    ).toMatchObject({
      status: "failed",
      checks: { generatedCursorEvidenceComplete: false },
      actual: { generatedCursors: [] },
    });
  });

  it("fails on positive resource growth, backlog, latency, and CPU beyond thresholds", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const strict: RetentionSoakThresholds = {
      ...thresholds,
      maximumArchiveBacklog: 0,
      maximumArchiveLatencyMs: 50,
      maximumOutboxPending: 0,
      maximumOutboxLagMs: 50,
      maximumCpuPercent: 5,
      maximumMemoryBytes: 15_000,
      maximumDatabaseRowsSlopePerHour: 0,
      maximumDatabaseBytesSlopePerHour: 0,
      maximumTableBytesSlopePerHour: 0,
      maximumDeadTuplesSlopePerHour: 0,
      maximumRedisLengthSlopePerHour: 0,
      maximumContainerMemorySlopeBytesPerHour: 0,
    };
    const baseline = sample();
    const finalSample = sample({
      sampledAt: end.toISOString(),
      archive: {
        planned: 0,
        uploaded: 0,
        verified: 2,
        verifiedRows: 2,
        failed: 0,
        pruned: 0,
        backlog: 1,
        maximumLatencyMs: 100,
        currentRunGenerated: 1,
        currentRunArchived: 1,
      },
      outbox: { pending: 1, maximumLagMs: 100 },
      redis: { length: 20, connections: 2 },
      database: {
        rows: 110,
        sizeBytes: 2_000,
        tableSizeBytes: 1_000,
        deadTuples: 10,
        connections: 3,
      },
      containers: {
        "workmesh-api": { cpuPercent: 10, memoryBytes: 20_000 },
      },
    });
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [finalSample],
        100,
        strict,
        1,
        ["101"],
      ),
    ).toMatchObject({
      status: "failed",
      checks: {
        archiveBacklogBounded: false,
        archiveBacklogConverged: false,
        outboxBounded: false,
        outboxConverged: false,
        latencyBounded: false,
        cpuBounded: false,
        memoryBounded: false,
        databaseRowsGrowthBounded: false,
        databaseBytesGrowthBounded: false,
        tableBytesGrowthBounded: false,
        deadTuplesGrowthBounded: false,
        redisGrowthBounded: false,
        containerMemoryGrowthBounded: false,
      },
    });
  });

  it("rejects a minute-scale growth spike even when the final sample recovers", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const middle = new Date("2026-07-28T00:01:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const strict: RetentionSoakThresholds = {
      ...thresholds,
      maximumDatabaseRowsSlopePerHour: 1,
      maximumDatabaseBytesSlopePerHour: 0,
      maximumTableBytesSlopePerHour: 0,
      maximumDeadTuplesSlopePerHour: 0,
      maximumRedisLengthSlopePerHour: 0,
      maximumContainerMemorySlopeBytesPerHour: 0,
    };
    const baseline = sample();
    const archive = {
      ...baseline.archive,
      verified: 2,
      verifiedRows: 2,
      currentRunGenerated: 1,
      currentRunArchived: 1,
    };
    const middleSample = sample({
      sampledAt: middle.toISOString(),
      archive,
      redis: { length: 20, connections: 2 },
      database: {
        rows: 120,
        sizeBytes: 2_000,
        tableSizeBytes: 1_000,
        deadTuples: 10,
        connections: 3,
      },
      containers: {
        "workmesh-api": { cpuPercent: 1, memoryBytes: 20_000 },
      },
    });
    const finalSample = sample({
      sampledAt: end.toISOString(),
      archive,
      redis: { length: 10, connections: 2 },
      database: {
        rows: 101,
        sizeBytes: 1_000,
        tableSizeBytes: 500,
        deadTuples: 0,
        connections: 3,
      },
    });
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [middleSample, finalSample],
        100,
        strict,
        2,
        ["101"],
      ),
    ).toMatchObject({
      status: "failed",
      checks: {
        databaseRowsGrowthBounded: false,
        databaseBytesGrowthBounded: false,
        tableBytesGrowthBounded: false,
        deadTuplesGrowthBounded: false,
        redisGrowthBounded: false,
        containerMemoryGrowthBounded: false,
      },
      actual: {
        endToEndSlopesPerHour: {
          databaseBytes: 0,
          tableBytes: 0,
          deadTuples: 0,
          redisLength: 0,
          containerMemoryBytes: { "workmesh-api": 0 },
        },
      },
    });
  });

  it("fails on missing samples, stale Worker, floor movement, or Redis overflow", () => {
    const start = new Date("2026-07-28T00:00:00Z");
    const end = new Date("2026-07-29T00:00:00Z");
    const baseline = sample();
    expect(
      retentionSoakReport(
        start,
        end,
        baseline,
        [
          sample({
            sampledAt: end.toISOString(),
            floor: "1",
            workerFresh: false,
            redis: { length: 101, connections: 2 },
          }),
        ],
        100,
        thresholds,
        2,
      ),
    ).toMatchObject({
      status: "failed",
      retentionFloorAdvanced: true,
      checks: {
        samplesComplete: false,
        workerStayedFresh: false,
        redisBounded: false,
      },
    });
  });
});
