const retentionSafeErrorCodes = new Set([
  "ARCHIVE_CUTOFF_RECHECK_FAILED",
  "ARCHIVE_MEMBER_ALREADY_FLOORED_ABOVE_FLOOR",
  "ARCHIVE_MEMBER_FLOOR_COUNT_MISMATCH",
  "ARCHIVE_MEMBERSHIP_FINALIZE_FAILED",
  "ARCHIVE_MEMBERSHIP_PARTIAL",
  "ARCHIVE_OBJECT_DECODE_FAILED",
  "ARCHIVE_OBJECT_JSON_INVALID",
  "ARCHIVE_OBJECT_MANIFEST_MISMATCH",
  "ARCHIVE_OBJECT_MEMBERSHIP_INVALID",
  "ARCHIVE_OBJECT_MISSING",
  "ARCHIVE_OBJECT_RECORD_INVALID",
  "ARCHIVE_OUTBOX_PROOF_MISSING",
  "ARCHIVE_PREFIX_RECHECK_FAILED",
  "ARCHIVE_RECORD_RECHECK_FAILED",
  "ARCHIVE_SEGMENT_MISSING",
  "ARCHIVE_SEGMENT_FENCE_LOST",
  "ARCHIVE_SNAPSHOT_RECHECK_FAILED",
  "ARTIFACT_CHECKSUM_MISMATCH",
  "ARTIFACT_METADATA_CHECKSUM_MISMATCH",
  "ARTIFACT_MIME_MISMATCH",
  "ARTIFACT_OBJECT_BODY_MISSING",
  "ARTIFACT_SIZE_MISMATCH",
  "EVENT_PRUNE_COUNT_MISMATCH",
  "EVENT_RETENTION_GAP",
  "REDIS_STREAM_EXACT_TRIM_FAILED",
  "RETENTION_CLAIM_LOST",
  "RETENTION_FLOOR_FENCE_LOST",
  "RETENTION_FLOOR_MISSING",
  "RETENTION_IO_TIMEOUT",
  "RETENTION_OBJECT_LOCK_DELETE_ALLOWED",
  "RETENTION_OBJECT_LOCK_MODE_MISMATCH",
  "RETENTION_OBJECT_LOCK_REQUIRED",
  "RETENTION_OBJECT_LOCK_TOO_SHORT",
  "RETENTION_OBJECT_VERSION_MISMATCH",
  "RETENTION_OBJECT_VERSION_REQUIRED",
  "RETENTION_PROGRESS_NOT_OBSERVED",
  "RETENTION_PROGRESS_STALE",
  "RETENTION_SCHEDULER_CLOSE_FAILED",
  "RETENTION_SCHEDULER_STOPPED",
]);

export type SafeRetentionErrorLog = Readonly<{
  safeErrorCode: string;
}>;

export const safeRetentionErrorCode = (error: unknown): string => {
  const candidate = error instanceof Error ? error.message : "";
  return retentionSafeErrorCodes.has(candidate)
    ? candidate
    : "RETENTION_JOB_FAILED";
};
