// Generated by packages/db/scripts/generate-v1-baseline.mts. Do not edit manually.

export type MigrationManifestEntry = Readonly<{
  version: string
  file: string
  checksumSha256: string
}>

export const legacyMigrationManifest = [
  { version: '0001_stage0', file: '0001_stage0.sql', checksumSha256: '06f655d3a26c4b3214b1e8c4fe944c13fbbea1b675d3c3a243a1badc7432490a' },
  { version: '0002_stage0_integrity_delivery', file: '0002_stage0_integrity_delivery.sql', checksumSha256: 'bbb1dbda54c39d17a5759011ca058f712c33620f9ee0bb0b537dadb909b489f3' },
  { version: '0003_stage1_agent_identity_delegation', file: '0003_stage1_agent_identity_delegation.sql', checksumSha256: 'dc90e1890a5a283ff186e6d91e36f7a3f4a1b61ad3a1a5b2324f5090f4943ad2' },
  { version: '0004_stage1_session_execution', file: '0004_stage1_session_execution.sql', checksumSha256: 'ec1518106ffc4512f2b49dc44247be604aaf73f69e42b891b38ec5f0c4684b5e' },
  { version: '0005_stage1_tokens_webhooks_events', file: '0005_stage1_tokens_webhooks_events.sql', checksumSha256: '73a3b64e6b16b695f7aa3176f52ecadd2952d300664202e0e1043a7c8a33da35' },
  { version: '0006_stage1_review_fixes', file: '0006_stage1_review_fixes.sql', checksumSha256: '27547908ec229881581d8f3fb18681e5d6045e1f70616a278513f36ad8ff6ff2' },
  { version: '0007_stage2_work_rooms_leases_handoffs', file: '0007_stage2_work_rooms_leases_handoffs.sql', checksumSha256: '1153c6262d249d85a938fa9e7b46f854cdc1d137df45023dbdfcff5e9967cf4d' },
  { version: '0008_stage3_delivery_control_plane', file: '0008_stage3_delivery_control_plane.sql', checksumSha256: 'cb989ff39eba11371e8cb679b4920ebbba620f846fd54a41cb17cda92396c3ea' },
  { version: '0009_stage3_production_adapters', file: '0009_stage3_production_adapters.sql', checksumSha256: 'eb10d61ea7800d330f35def815d88ce8ddbc25a58fa0654504ffb8241a089a81' },
  { version: '0010_stage3_provider_projection_provenance', file: '0010_stage3_provider_projection_provenance.sql', checksumSha256: '2e32bef6ee2f742f82cacb888da2d5004ae97b2f46a6f81e27b206fc0426f436' },
  { version: '0011_stage3_provider_review_projection', file: '0011_stage3_provider_review_projection.sql', checksumSha256: '77db88d09ab6fc03741f4527d95d44f6cbdb3407d13d143474592f4c611d9d09' },
  { version: '0012_stage3_regate_fencing_and_decisions', file: '0012_stage3_regate_fencing_and_decisions.sql', checksumSha256: '31f5c1258e6ae794ebdfae7e6f0115ab73249d6c937979fe88af5dcdd1291afa' },
  { version: '0013_stage3_audit_closure', file: '0013_stage3_audit_closure.sql', checksumSha256: 'b8d204e197be20ac823f7b24654be01054cbf26e4986b9fc9a6b53fd218d3df6' },
  { version: '0014_provider_action_kinds', file: '0014_provider_action_kinds.sql', checksumSha256: 'afe919a10aa8787e272bd0f66c51e183c60816358d34d82e7eb7037d4cdec290' },
  { version: '0015_stage4_planning_views_templates', file: '0015_stage4_planning_views_templates.sql', checksumSha256: '98f30b63a4a43d20be9f67ec2161ecb4907b4d1c57834dd903ada89bfba68f2b' },
  { version: '0016_stage4_usage_notifications', file: '0016_stage4_usage_notifications.sql', checksumSha256: '27b1ed53df61b202ce9d1b43d61ebec5d8d2bb6c20214814d0713fa3ba0b2500' },
  { version: '0017_stage4_automation_control_plane', file: '0017_stage4_automation_control_plane.sql', checksumSha256: '2d140501797f9b25ab2024c5114300538d521fc158129e55bb328354041078f0' },
  { version: '0018_stage4_loops_health_a2a', file: '0018_stage4_loops_health_a2a.sql', checksumSha256: 'e571477e0b1129fdd3a7b75f7ce9ceb0fdb3cd93e9826081364e33293a92066b' },
  { version: '0019_stage4_gitea', file: '0019_stage4_gitea.sql', checksumSha256: '625845b77ff4b92606898a2f3cf0864f6dee2a569d48650e33a80162d939f3ca' },
  { version: '0020_stage4_review_hardening', file: '0020_stage4_review_hardening.sql', checksumSha256: '3e8e5b0232aa263de72dfa1bed2a7d36242750bdbc5aeae1e72d71c533719a14' },
  { version: '0021_stage4_a2a_direction_and_prompt_identity', file: '0021_stage4_a2a_direction_and_prompt_identity.sql', checksumSha256: '9d62b327582cc3a3cff844a6dc72132214395146cfaad9a4d4e3a66b4f8502dd' },
  { version: '0022_route_policy_authorization_denials', file: '0022_route_policy_authorization_denials.sql', checksumSha256: '93865ea55f730cbd11a9cde2e9a9e16655d6e346b2a6368a350c79f87906ca7f' },
  { version: '0023_auth_idempotency_records', file: '0023_auth_idempotency_records.sql', checksumSha256: 'd3ac02a7c2a8a9182531e122b61552b9a69df0a6cdbd840e935c664d8487a688' },
  { version: '0024_cursor_pagination_indexes', file: '0024_cursor_pagination_indexes.sql', checksumSha256: 'd453dc9a38e30ed28bf424ff328806702c46d7bb9e4b9a68fc32daefc58ca17e' },
  { version: '0025_realtime_event_envelope', file: '0025_realtime_event_envelope.sql', checksumSha256: 'df3638b3c69c3b855b9ce9645de32ca748798a27c7b429f175bde3cb69ae915e' },
  { version: '0026_retention_archive_and_heartbeat_health', file: '0026_retention_archive_and_heartbeat_health.sql', checksumSha256: '6db3424019a98492e2cfccae4793bb15bbcbed24f263a5c5046cacbce173c15c' },
  { version: '0027_worker_runtime_identity', file: '0027_worker_runtime_identity.sql', checksumSha256: '6307e09d4862e10257dd03201f8fa51806525a4240eba546795f0041cf98ab96' },
  { version: '0028_worker_identity_conflict_count', file: '0028_worker_identity_conflict_count.sql', checksumSha256: 'b5d261a0ceac31ce08a72e83bcfca6c8d251d2093f8e767a9be793a0fc5d56b1' },
  { version: '0029_exact_archive_membership', file: '0029_exact_archive_membership.sql', checksumSha256: '98f7f181fb1e38a1d69f9c8c538ff99f8ee323415792041fb02f8482eb2039dc' },
  { version: '0030_durable_archive_upload_intents', file: '0030_durable_archive_upload_intents.sql', checksumSha256: '712bc5cd987c7d1f07e8967b03c1eb2d21b2cc7cfaeff79b36024af9a164eddf' },
  { version: '0031_agent_session_external_urls_shape', file: '0031_agent_session_external_urls_shape.sql', checksumSha256: '84ad62a856f1bc2d5d9c872c53a82818f4a3e4f440b377b19f1748cb1a348f2a' },
  { version: '0032_agent_inbox_receipts', file: '0032_agent_inbox_receipts.sql', checksumSha256: '45b8b1e06d96ce4764498b3d5ae96f1a4dd6aea13a1470f2510bdabe8c8f1eab' },
  { version: '0033_inbox_receipt_reply_binding', file: '0033_inbox_receipt_reply_binding.sql', checksumSha256: 'f04600d723c8aef76aca57f15f7a3c8ea70849970b2e573bcbbbbd14f5cfb086' },
  { version: '0034_legacy_inbox_scope_derivation', file: '0034_legacy_inbox_scope_derivation.sql', checksumSha256: '5d100a5a912489804e7a471a62b0551559f0438bfd898fb685d01b7981033171' },
  { version: '0035_decision_session_provenance', file: '0035_decision_session_provenance.sql', checksumSha256: '0680da47336f7188f7ce3f5ace4d8b6a11f7ac0fd503efa040c91a481c8a2084' },
  { version: '0036_approval_autonomy_policy', file: '0036_approval_autonomy_policy.sql', checksumSha256: '3a18472657d5a2017738c093b9d875ced9a6e214090dfb13fbb43cd5beb76880' },
  { version: '0037_browser_push', file: '0037_browser_push.sql', checksumSha256: '3c06693e8d95aab781a1bfd7028d87ab263e6dc75ad913e22c563683d51ae7c7' },
  { version: '0038_agent_enrollment_and_archive', file: '0038_agent_enrollment_and_archive.sql', checksumSha256: 'f3ffbe41b202b11d0fed78cc3d6e710bff2775b0630f137cc7b70c2fb06f1173' },
] as const satisfies readonly MigrationManifestEntry[]

export const v1MigrationManifest = [
  { version: '0001_v1_baseline', file: 'v1/0001_v1_baseline.sql', checksumSha256: '1fc1297ef9b4600d56368c6734b318b41b48776de82d5d9fe307d09427ce3f83' },
  { version: '0002_active_executor_projection', file: 'v1/0002_active_executor_projection.sql', checksumSha256: '0742da4ba547e484f463687e67392c3762e3628f2f841473cfde66c2725342d2' },
  { version: '0003_versioned_guidance', file: 'v1/0003_versioned_guidance.sql', checksumSha256: '199adac75057ed0a2b285453440359d68aea1ae62cba33b2274ac8e6364fa2e7' },
  { version: '0004_agent_connections', file: 'v1/0004_agent_connections.sql', checksumSha256: 'c31fde289828e87e7919cf114cccd24fb67ace2ee8007539a66273cfb6b90548' },
  { version: '0005_planning_domain_parity', file: 'v1/0005_planning_domain_parity.sql', checksumSha256: '1810ceb56156b7d0305b03b6b69b65453fb85d8b949afbfc78eed2ebf2295be4' },
  { version: '0006_human_attachments', file: 'v1/0006_human_attachments.sql', checksumSha256: '076f92a3257f9ad15c6c9770f31c12755d10a74e7f87b15b0363c391ec050ce5' },
  { version: '0007_active_milestone_name_uniqueness', file: 'v1/0007_active_milestone_name_uniqueness.sql', checksumSha256: 'a3313489a85a5aac71192f540cae57f84f29036a023018c7f2d295d7f5a87302' },
  { version: '0008_autonomous_control_push_enrollment', file: 'v1/0008_autonomous_control_push_enrollment.sql', checksumSha256: 'ca8ecf47510edfda6221de7f6f375c55d20d4cda588d39ff39816ebed24031d3' },
] as const satisfies readonly MigrationManifestEntry[]

export const legacyUpgradeBundleManifest = [
  { fromVersion: '0002_stage0_integrity_delivery', file: 'upgrades/from_0002_to_v1.sql', checksumSha256: '74149f3b8e715b1f9a1d57b408fa28a4659977b944bfdf4d3bd8de222a39d62e' },
  { fromVersion: '0006_stage1_review_fixes', file: 'upgrades/from_0006_to_v1.sql', checksumSha256: 'eec6410539fe3bd0ee1c2b48f476bbdf94024c7aa5542a02a4a782425329688e' },
  { fromVersion: '0007_stage2_work_rooms_leases_handoffs', file: 'upgrades/from_0007_to_v1.sql', checksumSha256: 'bbb60714eae06cb77614a8cc00736d69d96e60e1a2d33f84a64419cfd90ebb56' },
  { fromVersion: '0014_provider_action_kinds', file: 'upgrades/from_0014_to_v1.sql', checksumSha256: '795c395123856937f7770932ae8c24cff4ec71a8e4866b3abec625b4e1411929' },
  { fromVersion: '0021_stage4_a2a_direction_and_prompt_identity', file: 'upgrades/from_0021_to_v1.sql', checksumSha256: '14af5c1e1921cf010dff6623d8e9ef590d3957f530b5c7e56e6185246d5817d5' },
  { fromVersion: '0035_decision_session_provenance', file: 'upgrades/from_0035_to_v1.sql', checksumSha256: '167eeb06fbcf17fbf78d01ad601eae51013562d0ab487b94a929733221fe5657' },
] as const

export const supportedLegacyUpgradeEndpoints = [
  '0002_stage0_integrity_delivery',
  '0006_stage1_review_fixes',
  '0007_stage2_work_rooms_leases_handoffs',
  '0014_provider_action_kinds',
  '0021_stage4_a2a_direction_and_prompt_identity',
  '0035_decision_session_provenance',
] as const
