// Generated by scripts/generate-workmesh-skill-artifact.mjs.
export const workmeshSkillManifest = Object.freeze({
  name: 'workmesh' as const,
  version: '1.1.0',
  sha256: 'sha256:285a63525633b0624ab53ea9046c5526c2d464d0600dadf549789801b395466b',
  signature: 'ed25519:wjLEjEQcWES6d2XWlqgZQ1wdfN9BaQ03na1eEsD+DrhQVDY9QX3UeKOpXRR3NO2TXc5LSky4GpMod7U7zoxwCw==',
})
