// Generated by scripts/generate-workmesh-skill-artifact.mjs.
export const workmeshSkillManifest = Object.freeze({
  name: 'workmesh' as const,
  version: '1.1.0',
  sha256: 'sha256:59e09ba6183aed95491dfd8de053b06677a50d4a352cccac44fbe1dda3f58ec1',
  signature: 'ed25519:5FT9n6WG1OJaQvXXPCLvfEZVI7UHRWLFwTtgUInPZrFDqLI6bpXT+yjkffWDglC3iJg46IuwXOO3ySjDzR2zDA==',
})
