import { expect, test } from '@playwright/test'

test('Project and Issue documents keep immutable revisions through the real Web and API', async ({ page }) => {
  const projectName = `Document project ${Date.now()}`
  await page.goto('/?view=projects')
  await page.locator('.project-rail header').getByRole('button', { name: /新建项目|New project/ }).click()
  const createProject = page.getByTestId('create-project')
  await createProject.locator('input[name="name"]').fill(projectName)
  await createProject.getByRole('button', { name: /创建项目|Create project/ }).click()
  await expect(page.locator('.hcp-project-heading h1')).toHaveText(projectName)

  await page.locator('.project-detail-pane').getByRole('button', { name: /^(文档|Documents)$/ }).click()
  const manager = page.getByTestId('document-manager')
  await expect(manager).toBeVisible()
  await manager.getByRole('button', { name: /新建文档|New document/ }).click()
  await manager.locator('input[maxlength="180"]').fill('Project brief')
  await manager.locator('textarea[name="markdown"]').fill('# Project brief\n\nFirst revision.')
  await manager.getByRole('button', { name: /保存修订|Save revision/ }).click()
  await expect(manager.locator('.document-reading')).toContainText('First revision.')

  await manager.getByRole('button', { name: /^(编辑|Edit)$/ }).click()
  await manager.locator('textarea[name="markdown"]').fill('# Project brief\n\nSecond revision.')
  await manager.getByRole('button', { name: /保存修订|Save revision/ }).click()
  await expect(manager.locator('.document-reading')).toContainText('Second revision.')
  await manager.getByRole('button', { name: /^(历史|History)$/ }).click()
  const revisions = manager.locator('.document-history li button')
  await expect(revisions).toHaveCount(2)
  await revisions.nth(1).click()
  await expect(manager.locator('.document-history')).toContainText('First revision.')
  await manager.getByRole('button', { name: /恢复此版本为新修订|Restore this version as a new revision/ }).click()
  await expect(manager.locator('.document-reading')).toContainText('First revision.')
  await expect(manager.locator('.document-reading small')).toContainText('r3')
  await page.keyboard.press('Escape')
  await expect(manager).toBeHidden()

  await page.locator('.project-detail-pane').getByRole('button', { name: /新建 Issue|New issue/ }).click()
  const issueTitle = `Document issue ${Date.now()}`
  const createIssue = page.getByTestId('create-work-item')
  await createIssue.locator('input[name="title"]').fill(issueTitle)
  await createIssue.getByTestId('create-work-item-submit').click()
  await expect(createIssue).toBeHidden()
  await page.getByTestId('project-control-view-work').click()
  await page.locator('.project-detail-pane').getByRole('button', { name: issueTitle, exact: true }).click()
  const detail = page.locator('.work-item-detail-sheet')
  await detail.getByRole('tab', { name: /讨论|Discussion/ }).click()
  await detail.getByRole('button', { name: /^(文档|Documents)$/ }).click()
  await expect(manager).toBeVisible()
  await manager.getByRole('button', { name: /新建文档|New document/ }).click()
  await manager.locator('input[maxlength="180"]').fill('Issue runbook')
  await manager.locator('textarea[name="markdown"]').fill('# Issue runbook\n\nOwned by this Issue.')
  await manager.getByRole('button', { name: /保存修订|Save revision/ }).click()
  await expect(manager.locator('.document-reading')).toContainText('Owned by this Issue.')
})
