import { createHash, randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { applyMigrations, createDb, opaqueToken, tokenHash } from "@workmesh/db";
import { agentEventEnvelopeSchema, approvalDecisionResponseSchema, humanApprovalResponseSchema } from "@workmesh/contracts";
import { buildApp } from "../src/server.js";
import { seedAgentSessionBearer } from "./agent-session-test-credentials.js";

const databaseUrl = process.env.DATABASE_URL;
if (process.env.RUN_INTEGRATION !== "1" || !databaseUrl) throw new Error("API integration tests require RUN_INTEGRATION=1 and DATABASE_URL.");
if (!/(^|[_-])test(?:[_-]|$)/i.test(new URL(databaseUrl).pathname.slice(1))) throw new Error("API integration tests require a dedicated test database.");

const db = createDb(databaseUrl);
const app = buildApp();
type Page<T> = { items: T[]; nextCursor: string | null };
let cookie = "";
let csrf = "";
let actorId = "";
let teamId = "";
let readyId = "";
type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
type InjectResponse = { statusCode:number; headers:Record<string,string|string[]|number|undefined>; json:<T>()=>T };
const human = async (method: Method, url: string, payload?: object, headers: Record<string, string> = {}):Promise<InjectResponse> => await app.inject({ method, url, payload, headers: { cookie, "x-csrf-token": csrf, "idempotency-key": randomUUID(), ...headers } });
const agent = async (token: string, method: Method, url: string, payload?: object, headers: Record<string, string> = {}):Promise<InjectResponse> => await app.inject({ method, url, payload, headers: { authorization: `Bearer ${token}`, "idempotency-key": randomUUID(), ...headers } });
const payloadHash = (value: unknown) => `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;

describe("reviewer API fixes", () => {
  beforeAll(async () => {
    await applyMigrations(db); await db.query("TRUNCATE workspaces CASCADE");
    const install = await app.inject({ method: "POST", url: "/api/v1/auth/install", payload: { name: "Review", slug: "review", adminName: "Admin", email: "admin@review.test", password: "review-password" }, headers: { "idempotency-key": "review-install", "x-workmesh-bootstrap-token": process.env.WORKMESH_BOOTSTRAP_TOKEN! } });
    cookie = String(Array.isArray(install.headers["set-cookie"]) ? install.headers["set-cookie"][0] : install.headers["set-cookie"]).split(";")[0] ?? "";
    csrf = install.json<{ csrfToken: string }>().csrfToken;
    actorId = (await human("GET", "/api/v1/auth/me")).json<{ actor: { id: string } }>().actor.id;
    teamId = (await human("GET", "/api/v1/teams")).json<Page<{ id: string }>>().items[0]!.id;
    readyId = (await human("GET", `/api/v1/teams/${teamId}/states`)).json<Page<{ id: string; name: string }>>().items.find((state: {name:string}) => state.name === "Ready")!.id;
  });
  afterAll(async () => { await app.close(); await db.end(); });

  it("atomically delegates/starts, replays, scopes reads, returns guidance, and revokes access", async () => {
    const work = await human("POST", "/api/v1/work-items", { teamId, title: "Scoped work", statusId: readyId, priority: "none", labels: [], responsibleHumanActorId: actorId });
    const workItem = work.json<{ id: string; revision: number }>();
    const registered = await human("POST", "/api/v1/agents/register", { slug: "review-agent", name: "Review Agent", provider: "test", version: "1", supportedProtocols: ["native_http"], requestedCapabilities: ["work:read", "work:write", "plan:write"], approvedCapabilities: ["work:read", "work:write", "plan:write"], outputArtifactTypes: [], maxConcurrency: 1 });
    const definition = registered.json<{ id: string; revision: number }>();
    expect((await human("PUT", `/api/v1/agents/${definition.id}/team-access/${teamId}`, { approvedCapabilities: ["work:read", "work:write", "plan:write"] })).statusCode).toBe(200);
    const body = { agentId: definition.id, principalHumanActorId: actorId, role: "executor", requestedCapabilities: ["work:read", "work:write", "plan:write"], initialPrompt: "Start", budget: {} };
    const key = "atomic-review-start";
    const first = await human("POST", `/api/v1/work-items/${workItem.id}/agent-session`, body, { "if-match": `"revision-${workItem.revision}"`, "idempotency-key": key });
    const replay = await human("POST", `/api/v1/work-items/${workItem.id}/agent-session`, body, { "if-match": `"revision-${workItem.revision}"`, "idempotency-key": key });
    expect([first.statusCode, replay.statusCode]).toEqual([200, 200]);
    expect(replay.json()).toEqual(first.json());
    const scopeMismatch = await human("POST", `/api/v1/work-items/${workItem.id}/agent-session`, { ...body, requestedCapabilities: ["work:read"] }, { "if-match": `"revision-${workItem.revision}"` });
    expect(scopeMismatch.statusCode).toBe(403);
    expect(scopeMismatch.json<{error:{code:string}}>()).toMatchObject({error:{code:"CAPABILITY_DENIED"}});
    const started = first.json<{ delegation: { id: string }; session: { id: string } }>();
    expect((await db.query("SELECT count(*)::int AS count FROM domain_events WHERE aggregate_id=$1", [started.session.id])).rows[0]?.count).toBeGreaterThan(0);
    const token = await seedAgentSessionBearer(db, started.session.id, definition.id);
    const acknowledged = await agent(token, "POST", `/api/v1/agent-sessions/${started.session.id}/ack`, { summary: "ready", externalUrls: [] });
    expect(acknowledged.statusCode, JSON.stringify(acknowledged.json())).toBe(200);
    const executing = await agent(token, "POST", `/api/v1/agent-sessions/${started.session.id}/state`, { state: "executing", reason: "running" }, { "if-match": `"revision-${acknowledged.json<{revision:number}>().revision}"` });
    expect(executing.statusCode, JSON.stringify(executing.json())).toBe(200);
    expect((await agent(token, "GET", `/api/v1/work-items/${workItem.id}`)).statusCode).toBe(200);
    expect((await agent(token, "GET", `/api/v1/teams/${teamId}/guidance`)).statusCode).toBe(200);
    const removedRead = await human("PATCH", `/api/v1/agents/${definition.id}`, { approvedCapabilities: ["work:write", "plan:write"] }, { "if-match": `"revision-${definition.revision}"` });
    expect(removedRead.statusCode).toBe(200);
    expect((await agent(token, "GET", `/api/v1/work-items/${workItem.id}`)).statusCode).toBe(403);
    const restoredRead = await human("PATCH", `/api/v1/agents/${definition.id}`, { approvedCapabilities: ["work:read", "work:write", "plan:write"] }, { "if-match": `"revision-${removedRead.json<{revision:number}>().revision}"` });
    expect(restoredRead.statusCode).toBe(200);
    const other = await human("POST", "/api/v1/work-items", { teamId, title: "Other work", statusId: readyId, priority: "none", labels: [] });
    expect((await agent(token, "GET", `/api/v1/work-items/${other.json<{ id: string }>().id}`)).statusCode).toBe(403);
    const approvalPayload={operation:"authority preview"};
    const pendingApproval=await agent(token,"POST","/api/v1/approvals",{
      sessionId:started.session.id,approvalType:"protected_action",actionName:"authority.preview",
      actionPayloadSanitized:approvalPayload,actionPayloadHash:payloadHash(approvalPayload),riskLevel:"medium",
      rationaleSummary:"Verify live authority projection.",requiredApprovals:1,expiresAt:new Date(Date.now()+3600_000).toISOString(),
    });
    expect(pendingApproval.statusCode,JSON.stringify(pendingApproval.json())).toBe(200);
    const pendingApprovalId=pendingApproval.json<{id:string}>().id;
    expect(pendingApproval.json<Record<string,unknown>>()).not.toHaveProperty("viewer_actionability");
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"actionable",allowed_decisions:["approved","rejected"]});
    expect((await agent(token,"GET",`/api/v1/approvals/${pendingApprovalId}`)).json<Record<string,unknown>>()).not.toHaveProperty("viewer_actionability");
    expect((await human("PUT",`/api/v1/agents/${definition.id}/team-access/${teamId}`,{approvedCapabilities:["work:read","plan:write"]})).statusCode).toBe(200);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"authority_revoked"});
    const capabilityDriftDecision=await human("POST",`/api/v1/approvals/${pendingApprovalId}/decide`,{decision:"approved",reason:"must not pass capability drift"},{"if-match":"\"revision-1\""});
    expect(capabilityDriftDecision.statusCode).toBe(409);
    expect(capabilityDriftDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"DELEGATION_NOT_ACTIVE"}});
    expect((await human("PUT",`/api/v1/agents/${definition.id}/team-access/${teamId}`,{approvedCapabilities:["work:read","work:write","plan:write"]})).statusCode).toBe(200);
    const reducedDefinition=await human("PATCH",`/api/v1/agents/${definition.id}`,{approvedCapabilities:["work:read","plan:write"]},{"if-match":`"revision-${restoredRead.json<{revision:number}>().revision}"`});
    expect(reducedDefinition.statusCode).toBe(200);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"authority_revoked"});
    const definitionDriftDecision=await human("POST",`/api/v1/approvals/${pendingApprovalId}/decide`,{decision:"approved",reason:"must not pass definition drift"},{"if-match":"\"revision-1\""});
    expect(definitionDriftDecision.statusCode).toBe(409);
    const restoredDefinition=await human("PATCH",`/api/v1/agents/${definition.id}`,{approvedCapabilities:["work:read","work:write","plan:write"]},{"if-match":`"revision-${reducedDefinition.json<{revision:number}>().revision}"`});
    expect(restoredDefinition.statusCode).toBe(200);
    await db.query("UPDATE delegations SET capability_scope=jsonb_set(capability_scope,'{workItemIds}','[]'::jsonb,false) WHERE id=$1",[started.delegation.id]);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"authority_revoked"});
    const scopeDriftDecision=await human("POST",`/api/v1/approvals/${pendingApprovalId}/decide`,{decision:"approved",reason:"must not pass scope drift"},{"if-match":"\"revision-1\""});
    expect(scopeDriftDecision.statusCode).toBe(409);
    await db.query("UPDATE delegations SET capability_scope=jsonb_set(capability_scope,'{workItemIds}',jsonb_build_array($2::text),true) WHERE id=$1",[started.delegation.id,workItem.id]);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"actionable",allowed_decisions:["approved","rejected"]});
    await db.query("UPDATE delegations SET permissions_snapshot=ARRAY['work:read'] WHERE id=$1",[started.delegation.id]);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"authority_revoked"});
    const permissionsSnapshotDriftDecision=await human("POST",`/api/v1/approvals/${pendingApprovalId}/decide`,{decision:"approved",reason:"must not pass delegation capability drift"},{"if-match":"\"revision-1\""});
    expect(permissionsSnapshotDriftDecision.statusCode).toBe(409);
    expect(permissionsSnapshotDriftDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"DELEGATION_NOT_ACTIVE"}});
    await db.query("UPDATE delegations SET permissions_snapshot=ARRAY['work:read','work:write','plan:write'] WHERE id=$1",[started.delegation.id]);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"actionable",allowed_decisions:["approved","rejected"]});
    await db.query("UPDATE agent_team_access SET revoked_at=now() WHERE workspace_id=(SELECT workspace_id FROM approvals WHERE id=$1) AND agent_id=$2 AND team_id=$3",[pendingApprovalId,definition.id,teamId]);
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${pendingApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"authority_revoked"});
    const revokedDecision=await human("POST",`/api/v1/approvals/${pendingApprovalId}/decide`,{decision:"approved",reason:"must not pass"},{"if-match":"\"revision-1\""});
    expect(revokedDecision.statusCode).toBe(409);
    expect(revokedDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"DELEGATION_NOT_ACTIVE"}});
    await db.query("UPDATE agent_team_access SET revoked_at=NULL WHERE workspace_id=(SELECT workspace_id FROM approvals WHERE id=$1) AND agent_id=$2 AND team_id=$3",[pendingApprovalId,definition.id,teamId]);
    const revokedAccess = await human("DELETE", `/api/v1/agents/${definition.id}/team-access/${teamId}`);
    expect(revokedAccess.statusCode, JSON.stringify(revokedAccess.json())).toBe(200);
    expect((await agent(token, "GET", `/api/v1/work-items/${workItem.id}`)).statusCode).toBe(401);
  });

  it("persists definition approvals and prevents approval/requested capability drift", async () => {
    const registered = await human("POST", "/api/v1/agents/register", { slug: "definition-control", name: "Definition control", provider: "test", version: "1", supportedProtocols: ["native_http"], requestedCapabilities: ["work:read", "work:write"], approvedCapabilities: ["work:read"], outputArtifactTypes: [] });
    expect(registered.statusCode).toBe(200);
    let definition = registered.json<{ id:string; revision:number; approved_capabilities:string[] }>();
    expect(definition.approved_capabilities).toEqual(["work:read"]);
    const listed = (await human("GET", "/api/v1/agents")).json<Page<{id:string;approved_capabilities:string[]}>>().items;
    expect(listed.find(agent => agent.id === definition.id)?.approved_capabilities).toEqual(["work:read"]);
    const approved = await human("PATCH", `/api/v1/agents/${definition.id}`, { approvedCapabilities: ["work:read", "work:write"] }, { "if-match": `"revision-${definition.revision}"` });
    expect(approved.statusCode).toBe(200);
    definition = approved.json<{ revision:number; approved_capabilities:string[] }>() as typeof definition;
    expect(definition.approved_capabilities).toEqual(["work:read", "work:write"]);
    const reduced = await human("PATCH", `/api/v1/agents/${registered.json<{id:string}>().id}`, { requestedCapabilities: ["work:read"], approvedCapabilities: ["work:read"] }, { "if-match": `"revision-${definition.revision}"` });
    expect(reduced.statusCode).toBe(200);
    const outOfBounds = await human("PATCH", `/api/v1/agents/${registered.json<{id:string}>().id}`, { approvedCapabilities: ["plan:write"] }, { "if-match": `"revision-${reduced.json<{revision:number}>().revision}"` });
    expect(outOfBounds.statusCode).toBe(403);
  });

  it("enforces approval quorum, canonical consumption, plan gating, token refresh, context scope, webhook SSRF, and stale retry", async () => {
    const work = (await human("POST", "/api/v1/work-items", { teamId, title: "Approval work", statusId: readyId, priority: "none", labels: [], responsibleHumanActorId: actorId })).json<{id:string;revision:number}>();
    const otherWork = (await human("POST", "/api/v1/work-items", { teamId, title: "Other context", statusId: readyId, priority: "none", labels: [] })).json<{id:string}>();
    const registration = await human("POST", "/api/v1/agents/register", { slug: "approval-agent", name: "Approval Agent", provider: "test", version: "1", supportedProtocols: ["native_http"], requestedCapabilities: ["work:read", "work:write", "plan:write"], approvedCapabilities: ["work:read", "work:write", "plan:write"], outputArtifactTypes: [], maxConcurrency: 2 });
    const definition=registration.json<{id:string;installation_token:string}>();
    process.env.ALLOW_PRIVATE_AGENT_WEBHOOKS="true";
    const webhook=(await human("POST",`/api/v1/agents/${definition.id}/webhook-endpoints`,{url:"http://127.0.0.2:9999"})).json<{id:string}>();
    const webhookRevision=(await db.query<{revision:number}>("SELECT revision FROM agent_definitions WHERE id=$1",[definition.id])).rows[0]!.revision;
    expect((await human("POST",`/api/v1/agents/${definition.id}/webhook-endpoints/${webhook.id}/rotate-secret`,{}, {"if-match":`"revision-${webhookRevision}"`})).statusCode).toBe(200);
    delete process.env.ALLOW_PRIVATE_AGENT_WEBHOOKS;
    await human("PUT",`/api/v1/agents/${definition.id}/team-access/${teamId}`,{approvedCapabilities:["work:read","work:write","plan:write"]});
    const started=(await human("POST",`/api/v1/work-items/${work.id}/agent-session`,{agentId:definition.id,principalHumanActorId:actorId,role:"executor",requestedCapabilities:["work:read","work:write","plan:write"],initialPrompt:"Approve",budget:{}},{"if-match":`"revision-${work.revision}"`})).json<{session:{id:string;revision:number}}>();
    const oldToken=await seedAgentSessionBearer(db,started.session.id,definition.id);
    const ack=await agent(oldToken,"POST",`/api/v1/agent-sessions/${started.session.id}/ack`,{summary:"ack",externalUrls:[]});
    const executing=await agent(oldToken,"POST",`/api/v1/agent-sessions/${started.session.id}/state`,{state:"executing",reason:"run"},{"if-match":`"revision-${ack.json<{revision:number}>().revision}"`});
    const refresh=await app.inject({method:"POST",url:`/api/v1/agent-sessions/${started.session.id}/token/refresh`,payload:{},headers:{authorization:`Bearer ${definition.installation_token}`,"idempotency-key":randomUUID()}});
    const token=refresh.json<{sessionToken:string}>().sessionToken;
    expect((await agent(oldToken,"GET",`/api/v1/agent-sessions/${started.session.id}`)).statusCode).toBe(200);
    expect((await agent(token,"GET",`/api/v1/agent-sessions/${started.session.id}`)).statusCode).toBe(200);
    const foreignContext=(await db.query<{id:string}>("INSERT INTO context_snapshots(workspace_id,work_item_id,manifest,content_hash,created_by_actor_id) SELECT workspace_id,$1,'{}'::jsonb,$2,id FROM actors WHERE id=$3 RETURNING id",[otherWork.id,createHash("sha256").update(otherWork.id).digest("hex"),actorId])).rows[0]!.id;
    const contextTarget=(await human("POST", "/api/v1/work-items", { teamId, title: "Context target", statusId: readyId, priority: "none", labels: [], responsibleHumanActorId: actorId })).json<{id:string;revision:number}>();
    const context=await human("POST",`/api/v1/work-items/${contextTarget.id}/agent-session`,{agentId:definition.id,principalHumanActorId:actorId,role:"executor",requestedCapabilities:["work:read","work:write","plan:write"],initialPrompt:"bad context",contextSnapshotId:foreignContext,budget:{}},{"if-match":`"revision-${contextTarget.revision}"`});
    expect(context.statusCode).toBeGreaterThanOrEqual(400);
    const secretPayload={nested:{note:"Bearer abcdefghijklmnopqrstuvwxyz"}};
    expect((await agent(token,"POST","/api/v1/approvals",{sessionId:started.session.id,approvalType:"plan",actionName:"agent.plan.publish",actionPayloadSanitized:secretPayload,actionPayloadHash:payloadHash(secretPayload),riskLevel:"high",rationaleSummary:"secret check",requiredApprovals:1,expiresAt:new Date(Date.now()+3600_000).toISOString()})).statusCode).toBe(400);
    const expiredAction={expired:true}; const expired=await agent(token,"POST","/api/v1/approvals",{sessionId:started.session.id,approvalType:"plan",actionName:"agent.plan.publish",actionPayloadSanitized:expiredAction,actionPayloadHash:payloadHash(expiredAction),riskLevel:"high",rationaleSummary:"expire",requiredApprovals:1,expiresAt:new Date(Date.now()+3600_000).toISOString()}); const expiredId=expired.json<{id:string}>().id; await db.query("UPDATE approvals SET created_at=now()-interval '2 minutes',expires_at=now()-interval '1 second' WHERE id=$1",[expiredId]); expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${expiredId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"expired"}); const expiredDecision=await human("POST",`/api/v1/approvals/${expiredId}/decide`,{decision:"approved",reason:"late"},{"if-match":"\"revision-1\""}); expect(expiredDecision.statusCode).toBe(400); expect(expiredDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"APPROVAL_EXPIRED"}});
    const action={plan:"ship"}; const hash=payloadHash(action);
    const approval=await agent(token,"POST","/api/v1/approvals",{sessionId:started.session.id,approvalType:"plan",actionName:"agent.plan.publish",actionPayloadSanitized:action,actionPayloadHash:hash,riskLevel:"high",rationaleSummary:"need two",requiredApprovals:2,expiresAt:new Date(Date.now()+3600_000).toISOString()});
    const approvalId=approval.json<{id:string;revision:number}>().id;
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${approvalId}`)).json()).viewer_actionability.status).toBe("actionable");
    const first=await human("POST",`/api/v1/approvals/${approvalId}/decide`,{decision:"approved",reason:"one"},{"if-match":"\"revision-1\""}); expect(first.json<{status:string}>().status).toBe("pending"); expect(approvalDecisionResponseSchema.parse(first.json()).approval.viewer_actionability).toEqual({status:"blocked",reason:"viewer_already_decided"});
    const staleDecision=await human("POST",`/api/v1/approvals/${approvalId}/decide`,{decision:"approved",reason:"stale"},{"if-match":"\"revision-1\""}); expect(staleDecision.statusCode).toBe(409); expect(staleDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"REVISION_CONFLICT"}});
    expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${approvalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"viewer_already_decided"});
    const secondActor=randomUUID(), secondToken=opaqueToken(), secondCsrf=opaqueToken(); await db.query("INSERT INTO actors(id,workspace_id,kind,workspace_role,email,display_name,password_hash) SELECT $1,workspace_id,'human','member',$2,'Second','unused' FROM actors WHERE id=$3",[secondActor,"second@review.test",actorId]); await db.query("INSERT INTO memberships(workspace_id,team_id,actor_id,role) SELECT workspace_id,$1,$2,'member' FROM actors WHERE id=$3",[teamId,secondActor,actorId]); await db.query("INSERT INTO sessions(actor_id,token_hash,csrf_token,expires_at) VALUES($1,$2,$3,now()+interval '1 hour')",[secondActor,tokenHash(secondToken),secondCsrf]);
    const secondRead=await app.inject({method:"GET",url:`/api/v1/approvals/${approvalId}`,headers:{cookie:`workmesh_session=${secondToken}`,"x-csrf-token":secondCsrf}}); expect(humanApprovalResponseSchema.parse(secondRead.json()).viewer_actionability.status).toBe("actionable");
    const second=await app.inject({method:"POST",url:`/api/v1/approvals/${approvalId}/decide`,payload:{decision:"approved",reason:"two"},headers:{cookie:`workmesh_session=${secondToken}`,"x-csrf-token":secondCsrf,"idempotency-key":randomUUID(),"if-match":"\"revision-2\""}}); expect(second.statusCode,JSON.stringify(second.json())).toBe(200); expect(second.json<{status:string}>().status).toBe("approved"); expect(approvalDecisionResponseSchema.parse(second.json()).status).toBe("approved"); expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${approvalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"already_decided"});
    const delivery=(await db.query<{payload:unknown}>("SELECT payload FROM agent_webhook_deliveries WHERE session_id=$1 AND event_type='approval.approved'",[started.session.id])).rows[0];
    expect(delivery?.payload).toMatchObject({sessionId:started.session.id,status:"approved"});
    const events=(await human("GET","/api/v1/events")).json<Array<Record<string,unknown>>>().filter(event=>event.aggregate_id===approvalId);
    const approvalEvents=events.filter(event=>String(event.event_type).startsWith("approval."));
    expect(approvalEvents.map(event=>event.event_type)).toEqual(expect.arrayContaining(["approval.requested","approval.decision.recorded","approval.approved"]));
    approvalEvents.forEach(event=>agentEventEnvelopeSchema.parse(event));
    const sequences=approvalEvents.map(event=>Number(event.sequence));
    expect(sequences.every((sequence,index)=>sequence>0 && (index===0 || sequence>sequences[index-1]!))).toBe(true);
    const inactivePayload={operation:"inactive session"}; const inactiveApproval=await agent(token,"POST","/api/v1/approvals",{sessionId:started.session.id,approvalType:"protected_action",actionName:"session.inactive",actionPayloadSanitized:inactivePayload,actionPayloadHash:payloadHash(inactivePayload),riskLevel:"medium",rationaleSummary:"Must become unavailable when execution stops.",requiredApprovals:1,expiresAt:new Date(Date.now()+3600_000).toISOString()}); const inactiveApprovalId=inactiveApproval.json<{id:string}>().id;
    const awaiting=await agent(token,"POST",`/api/v1/agent-sessions/${started.session.id}/state`,{state:"awaiting_approval",reason:"gate"},{"if-match":`"revision-${executing.json<{revision:number}>().revision}"`});
    const plan={changeSummary:"approved",steps:[{id:randomUUID(),title:"ship",ordinal:0}]};
    const missingApproval = await agent(token,"PUT",`/api/v1/agent-sessions/${started.session.id}/plan`,plan,{"if-match":`"revision-${awaiting.json<{revision:number}>().revision}"`});
    expect(missingApproval.statusCode).toBe(403);
    expect(missingApproval.json<{error:{code:string}}>()).toMatchObject({error:{code:"APPROVAL_REQUIRED"}});
    const wrong=await agent(token,"PUT",`/api/v1/agent-sessions/${started.session.id}/plan`,{...plan,approvalId,approvalPayloadHash:payloadHash({plan:"changed"})},{"if-match":`"revision-${awaiting.json<{revision:number}>().revision}"`}); expect(wrong.statusCode).toBe(400);
    const published=await agent(token,"PUT",`/api/v1/agent-sessions/${started.session.id}/plan`,{...plan,approvalId,approvalPayloadHash:hash},{"if-match":`"revision-${awaiting.json<{revision:number}>().revision}"`}); expect(published.statusCode).toBe(200);
    expect((await agent(token,"POST",`/api/v1/approvals/${approvalId}/consume`,{actionPayloadHash:hash},{"if-match":"\"revision-4\""})).statusCode).toBeGreaterThanOrEqual(400);
    const stopping=await human("POST",`/api/v1/agent-sessions/${started.session.id}/signals`,{signal:"stop",reason:"stop refresh"},{"if-match":`"revision-${published.json<{revision:number}>().revision}"`}); expect(stopping.statusCode).toBe(200); expect((await app.inject({method:"POST",url:`/api/v1/agent-sessions/${started.session.id}/token/refresh`,payload:{},headers:{authorization:`Bearer ${definition.installation_token}`,"idempotency-key":randomUUID()}})).statusCode).toBe(409); expect(humanApprovalResponseSchema.parse((await human("GET",`/api/v1/approvals/${inactiveApprovalId}`)).json()).viewer_actionability).toEqual({status:"blocked",reason:"session_inactive"}); const inactiveDecision=await human("POST",`/api/v1/approvals/${inactiveApprovalId}/decide`,{decision:"approved",reason:"must not pass"},{"if-match":"\"revision-1\""}); expect(inactiveDecision.statusCode).toBe(409); expect(inactiveDecision.json<{error:{code:string}}>()).toMatchObject({error:{code:"DELEGATION_NOT_ACTIVE"}});
    const endpoint=`/api/v1/agents/${definition.id}/webhook-endpoints`; expect((await human("POST",endpoint,{url:"http://127.0.0.1:9999"})).statusCode).toBe(400); process.env.ALLOW_PRIVATE_AGENT_WEBHOOKS="true"; expect((await human("POST",endpoint,{url:"http://127.0.0.1:9999"})).statusCode).toBe(200); delete process.env.ALLOW_PRIVATE_AGENT_WEBHOOKS;
    await db.query("UPDATE agent_sessions SET state='stale',revision=revision+1 WHERE id=$1",[started.session.id]); const stale=(await db.query<{revision:number}>("SELECT revision FROM agent_sessions WHERE id=$1",[started.session.id])).rows[0]!; const retry=await human("POST",`/api/v1/agent-sessions/${started.session.id}/retry`,{reason:"timeout",reuseContext:true},{"if-match":`"revision-${stale.revision}"`}); expect(retry.statusCode).toBe(200); expect((await db.query<{state:string}>("SELECT state FROM agent_sessions WHERE id=$1",[started.session.id])).rows[0]?.state).toBe("canceled");
    expect((await app.inject({method:"POST",url:`/api/v1/agent-sessions/${started.session.id}/token/refresh`,payload:{},headers:{authorization:`Bearer ${definition.installation_token}`,"idempotency-key":randomUUID()}})).statusCode).toBeGreaterThanOrEqual(400);
  });
});
