import type { Pool } from "pg";
import type { FastifyInstance, FastifyRequest } from "fastify";
import { lookup } from "node:dns/promises";
import net from "node:net";
import { z } from "zod";
import {
  acknowledgeAgentSessionInputSchema, agentPatchSchema, agentRegistrationInputSchema, appendActivityInputSchema, exchangeAgentSessionTokenInputSchema,
  artifactInputSchema, completeAgentSessionInputSchema, createAgentSessionInputSchema, decideApprovalInputSchema,
  delegationInputSchema, failAgentSessionInputSchema, heartbeatInputSchema, promptAgentSessionInputSchema,
  publishPlanInputSchema, requestApprovalInputSchema, signalAgentSessionInputSchema, stopAcknowledgementInputSchema, agentSessionStateSchema, retryAgentSessionInputSchema, refreshAgentSessionTokenInputSchema, delegateAndStartAgentSessionInputSchema, consumeApprovalInputSchema,
} from "@workmesh/contracts";
import { DomainError, parseRevision } from "@workmesh/domain";
import * as commands from "./commands.js";
import type { ApiActor, RequestMeta } from "./types.js";
import { authClientContext } from "../auth-idempotency.js";

type Helpers = { db: Pool; meta: (request: FastifyRequest, body: unknown, params?: Record<string, unknown>) => RequestMeta; header: (request: FastifyRequest, name: string) => string | undefined; readableTeam: (request: FastifyRequest, teamId: string) => Promise<void> };
const id = (request: FastifyRequest) => z.object({ id: z.string().uuid() }).parse(request.params).id;
const actor = (request: FastifyRequest) => request.actor as unknown as ApiActor;
const needHuman = (request: FastifyRequest) => { if (actor(request).kind !== "human") throw new DomainError("FORBIDDEN", "Human session required"); };
const needAdmin = (request: FastifyRequest) => { if (actor(request).kind !== "human" || actor(request).workspaceRole !== "admin") throw new DomainError("FORBIDDEN", "Workspace administrator role is required"); };
const privateIp = (address: string) => address === "::1" || address.startsWith("fe80:") || address.startsWith("fc") || address.startsWith("fd") || /^127\./.test(address) || /^10\./.test(address) || /^192\.168\./.test(address) || /^169\.254\./.test(address) || /^172\.(1[6-9]|2\d|3[01])\./.test(address);
export const assertWebhookUrl = async (raw: string): Promise<void> => { const url = new URL(raw); if (url.protocol !== "http:" && url.protocol !== "https:") throw new DomainError("VALIDATION_ERROR", "Webhook URL must use HTTP or HTTPS"); if (process.env.ALLOW_PRIVATE_AGENT_WEBHOOKS === "true") return; if (url.hostname === "localhost") throw new DomainError("VALIDATION_ERROR", "Private webhook targets are disabled"); const addresses = net.isIP(url.hostname) ? [{ address: url.hostname }] : await lookup(url.hostname, { all: true }); if (addresses.some(entry => privateIp(entry.address))) throw new DomainError("VALIDATION_ERROR", "Private webhook targets are disabled"); };
const agentOwnsSession = (request: FastifyRequest, sessionId: string) => { const current = actor(request); if (current.kind === "agent" && current.agentSessionId !== sessionId) throw new DomainError("RESOURCE_SCOPE_DENIED", "Agent token is scoped to its current session"); };
const sessionQuery = z.object({ teamId: z.string().uuid().optional(), workItemId: z.string().uuid().optional(), agentId: z.string().uuid().optional(), principalHumanActorId: z.string().uuid().optional(), state: z.string().optional() });

async function readableSession(request: FastifyRequest, h: Helpers, sessionId: string) {
  agentOwnsSession(request, sessionId);
  const session = (await h.db.query<{ id:string; team_id:string; work_item_id:string|null; project_id:string|null; delegation_status:string; permissions_snapshot:string[]; capability_scope:{teamIds?:string[];workItemIds?:string[];projectIds?:string[]}; agent_active:boolean; definition_capabilities:string[]; team_capabilities:string[]|null }>(`SELECT s.id,s.team_id,s.work_item_id,s.project_id,d.status AS delegation_status,d.permissions_snapshot,d.capability_scope,a.is_active AS agent_active,a.approved_capabilities AS definition_capabilities,ata.approved_capabilities AS team_capabilities FROM agent_sessions s JOIN delegations d ON d.id=s.delegation_id JOIN agent_definitions a ON a.id=s.agent_id LEFT JOIN agent_team_access ata ON ata.workspace_id=s.workspace_id AND ata.agent_id=s.agent_id AND ata.team_id=s.team_id AND ata.revoked_at IS NULL WHERE s.id=$1 AND s.workspace_id=$2`, [sessionId, actor(request).workspaceId])).rows[0];
  if (!session) throw new DomainError("NOT_FOUND", "Agent session not found");
  if (actor(request).kind === "human") { await h.readableTeam(request, session.team_id); return session; }
  const scope = session.capability_scope ?? {};
  const subject = session.work_item_id ?? session.project_id;
  if (!session.agent_active || session.delegation_status !== "active" || !session.permissions_snapshot.includes("work:read") || !session.definition_capabilities.includes("work:read") || !session.team_capabilities?.includes("work:read") || !scope.teamIds?.includes(session.team_id) || (subject && !scope.workItemIds?.includes(subject) && !scope.projectIds?.includes(subject))) throw new DomainError("RESOURCE_SCOPE_DENIED", "Agent token lacks read scope for this session");
  return session;
}

export function registerAgentRoutes(app: FastifyInstance, h: Helpers): void {
  app.get("/api/v1/agents", async request => {
    needHuman(request);
    return (await h.db.query(
      `SELECT a.*, COALESCE(
         jsonb_agg(jsonb_build_object(
           'agent_id', ata.agent_id, 'team_id', ata.team_id,
           'approved_capabilities', ata.approved_capabilities,
           'status', CASE WHEN ata.revoked_at IS NULL THEN 'active' ELSE 'revoked' END,
           'approved_by_actor_id', ata.granted_by_actor_id,
           'revision', a.revision, 'created_at', ata.created_at,
           'updated_at', ata.created_at, 'revoked_at', ata.revoked_at
         ) ORDER BY ata.created_at) FILTER (WHERE ata.agent_id IS NOT NULL), '[]'::jsonb
       ) AS team_access
       FROM agent_definitions a
       LEFT JOIN agent_team_access ata ON ata.workspace_id=a.workspace_id AND ata.agent_id=a.id
       WHERE a.workspace_id=$1
       GROUP BY a.id
       ORDER BY a.display_name`,
      [actor(request).workspaceId],
    )).rows;
  });
  app.post("/api/v1/agents/register", async request => { const body=agentRegistrationInputSchema.parse(request.body); if(body.endpointUrl) await assertWebhookUrl(body.endpointUrl); return commands.registerAgent(h.db,h.meta(request,body),body); });
  app.get("/api/v1/agents/:id", async request => { needHuman(request); const row = (await h.db.query("SELECT * FROM agent_definitions WHERE id=$1 AND workspace_id=$2", [id(request), actor(request).workspaceId])).rows[0]; if (!row) throw new DomainError("NOT_FOUND", "Agent not found"); return row; });
  app.patch("/api/v1/agents/:id", async request => { const body = agentPatchSchema.parse(request.body); if(body.endpointUrl) await assertWebhookUrl(body.endpointUrl); const agentId = id(request); return commands.updateAgent(h.db, h.meta(request, body, { id: agentId }), agentId, parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agents/:id/webhook-endpoints", async request => { needAdmin(request); const body = z.object({ url: z.string().url() }).parse(request.body); await assertWebhookUrl(body.url); const agentId = id(request); return commands.createWebhookEndpoint(h.db,h.meta(request,body,{id:agentId}),agentId,body.url); });
  app.post("/api/v1/agents/:id/webhook-endpoints/:endpointId/rotate-secret", async request => commands.rotateWebhookSecret(h.db, h.meta(request, {}, request.params as Record<string, unknown>), id(request), z.object({ endpointId: z.string().uuid() }).parse(request.params).endpointId, parseRevision(h.header(request, "if-match"))));
  app.put("/api/v1/agents/:id/team-access/:teamId", async request => { const body = z.object({ approvedCapabilities: z.array(z.string()).min(1) }).parse(request.body); return commands.grantAgentTeamAccess(h.db, h.meta(request, body, request.params as Record<string, unknown>), id(request), z.object({ teamId: z.string().uuid() }).parse(request.params).teamId, body.approvedCapabilities as never); });
  app.delete("/api/v1/agents/:id/team-access/:teamId", async request => commands.revokeAgentTeamAccess(h.db, h.meta(request, {}, request.params as Record<string, unknown>), id(request), z.object({ teamId: z.string().uuid() }).parse(request.params).teamId));

  app.post("/api/v1/work-items/:id/delegations", async request => { const body = delegationInputSchema.parse(request.body); const workItemId = id(request); return commands.createDelegation(h.db, h.meta(request, body, { id: workItemId }), workItemId, body); });
  app.post("/api/v1/work-items/:id/agent-session", async request => { const body = delegateAndStartAgentSessionInputSchema.parse(request.body); const workItemId = id(request); return commands.delegateAndStartAgentSession(h.db, h.meta(request, body, { id: workItemId }), workItemId, parseRevision(h.header(request, "if-match")), body); });
  app.get("/api/v1/delegations/:id", async request => { needHuman(request); const row = (await h.db.query("SELECT * FROM delegations WHERE id=$1 AND workspace_id=$2", [id(request), actor(request).workspaceId])).rows[0] as { team_id?: string } | undefined; if (!row) throw new DomainError("NOT_FOUND", "Delegation not found"); await h.readableTeam(request, row.team_id!); return row; });
  app.post("/api/v1/delegations/:id/revoke", async request => commands.revokeDelegation(h.db,h.meta(request,{}, {id:id(request)}),id(request),parseRevision(h.header(request,"if-match"))));

  app.get("/api/v1/agent-sessions", async request => { const query = sessionQuery.parse(request.query); const current = actor(request); const values: unknown[] = [current.workspaceId]; const where = ["s.workspace_id=$1"]; if (current.kind === "agent") { await readableSession(request,h,current.agentSessionId!); values.push(current.agentSessionId!); where.push(`s.id=$${values.length}`); } else if(current.workspaceRole!=="admin"){ values.push(current.id); where.push(`EXISTS(SELECT 1 FROM memberships m WHERE m.workspace_id=s.workspace_id AND m.team_id=s.team_id AND m.actor_id=$${values.length})`); } for (const [column, value] of Object.entries({ "s.team_id": query.teamId, "s.work_item_id": query.workItemId, "s.agent_id": query.agentId, "d.principal_human_actor_id": query.principalHumanActorId, "s.state": query.state })) if (value) { values.push(value); where.push(`${column}=$${values.length}`); } return (await h.db.query(`SELECT s.*,d.principal_human_actor_id,coalesce((a.manifest->>'heartbeatIntervalSeconds')::int,30) AS heartbeat_interval_seconds,s.created_at+interval '10 seconds' AS ack_deadline FROM agent_sessions s JOIN delegations d ON d.id=s.delegation_id JOIN agent_definitions a ON a.id=s.agent_id WHERE ${where.join(" AND ")} ORDER BY s.updated_at DESC`, values)).rows; });
  app.post("/api/v1/agent-sessions", async request => { const body = createAgentSessionInputSchema.parse(request.body); return commands.createAgentSession(h.db, h.meta(request, body), body); });
  app.post("/api/v1/agent-sessions/:id/token/exchange", async request => { const body = exchangeAgentSessionTokenInputSchema.parse(request.body); const bearer = h.header(request, "authorization")?.replace(/^Bearer\s+/i, ""); if (!bearer) throw new DomainError("UNAUTHENTICATED", "Installation bearer token is required"); return commands.exchangeAgentToken(h.db, { sessionId: id(request), nonce: body.exchangeToken, installationBearer: bearer, idempotencyKey: request.idempotencyKey!, clientContext: authClientContext(request) }); });
  app.post("/api/v1/agent-sessions/:id/token/refresh", async request => { const body = refreshAgentSessionTokenInputSchema.parse(request.body); const bearer = h.header(request, "authorization")?.replace(/^Bearer\s+/i, ""); if (!bearer) throw new DomainError("UNAUTHENTICATED", "Installation bearer token is required"); return commands.refreshAgentToken(h.db,{ sessionId:id(request), tokenId:body.tokenId, installationBearer:bearer, idempotencyKey:request.idempotencyKey!, clientContext:authClientContext(request) }); });
  app.get("/api/v1/agent-sessions/:id", async request => { const sessionId = id(request); await readableSession(request,h,sessionId); const row = (await h.db.query("SELECT s.*,coalesce((a.manifest->>'heartbeatIntervalSeconds')::int,30) AS heartbeat_interval_seconds,s.created_at+interval '10 seconds' AS ack_deadline FROM agent_sessions s JOIN agent_definitions a ON a.id=s.agent_id WHERE s.id=$1 AND s.workspace_id=$2", [sessionId, actor(request).workspaceId])).rows[0]; if (!row) throw new DomainError("NOT_FOUND", "Agent session not found"); return row; });
  app.post("/api/v1/agent-sessions/:id/ack", async request => { const body = acknowledgeAgentSessionInputSchema.parse(request.body); return commands.acknowledge(h.db, h.meta(request, body, { id: id(request) }), id(request), body); });
  app.post("/api/v1/agent-sessions/:id/heartbeat", async request => { const body = heartbeatInputSchema.parse(request.body); return commands.heartbeat(h.db, h.meta(request, body, { id: id(request) }), id(request), body); });
  app.post("/api/v1/agent-sessions/:id/state", async request => { const body = z.object({ state: agentSessionStateSchema, reason: z.string().min(1).max(2_000) }).parse(request.body); return commands.transitionState(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agent-sessions/:id/prompt", async request => { const body = promptAgentSessionInputSchema.parse(request.body); return commands.prompt(h.db, h.meta(request, body, { id: id(request) }), id(request), body); });
  app.post("/api/v1/agent-sessions/:id/activities", async request => { const body = appendActivityInputSchema.parse(request.body); return commands.appendActivity(h.db, h.meta(request, body, { id: id(request) }), id(request), body); });
  app.get("/api/v1/agent-sessions/:id/activities", async request => { const sessionId = id(request); await readableSession(request,h,sessionId); return (await h.db.query("SELECT * FROM agent_activities WHERE session_id=$1 ORDER BY sequence", [sessionId])).rows; });
  app.get("/api/v1/agent-sessions/:id/plan", async request => { const sessionId = id(request); const session=await readableSession(request,h,sessionId); const version=(await h.db.query<{current_plan_version_id:string|null}>("SELECT current_plan_version_id FROM agent_sessions WHERE id=$1",[session.id])).rows[0]?.current_plan_version_id; if (!version) return null; const plan = (await h.db.query("SELECT * FROM agent_plan_versions WHERE id=$1", [version])).rows[0]; const steps = (await h.db.query("SELECT * FROM agent_plan_steps WHERE plan_version_id=$1 ORDER BY ordinal", [version])).rows; return { ...plan as object, steps }; });
  app.get("/api/v1/agent-sessions/:id/plans", async request => { const sessionId = id(request); await readableSession(request,h,sessionId); const versions = (await h.db.query<{ id: string }>("SELECT * FROM agent_plan_versions WHERE session_id=$1 ORDER BY revision", [sessionId])).rows; return await Promise.all(versions.map(async version => ({ ...version, steps: (await h.db.query("SELECT * FROM agent_plan_steps WHERE plan_version_id=$1 ORDER BY ordinal", [version.id])).rows }))); });
  app.get("/api/v1/agent-sessions/:id/context", async request => { const sessionId = id(request); await readableSession(request,h,sessionId); const session=(await h.db.query("SELECT * FROM agent_sessions WHERE id=$1 AND workspace_id=$2",[sessionId,actor(request).workspaceId])).rows[0] as {team_id:string;work_item_id:string|null;project_id:string|null;current_plan_version_id:string|null;context_snapshot_id:string|null}|undefined; if(!session) throw new DomainError("NOT_FOUND","Agent session not found"); const workItem=session.work_item_id ? (await h.db.query("SELECT w.*,t.key AS team_key,s.name AS status_name,s.category AS status_category FROM work_items w JOIN teams t ON t.id=w.team_id JOIN workflow_states s ON s.id=w.status_id WHERE w.id=$1",[session.work_item_id])).rows[0] ?? null:null; const plan=session.current_plan_version_id ? (await h.db.query("SELECT * FROM agent_plan_versions WHERE id=$1",[session.current_plan_version_id])).rows[0] ?? null:null; const planWithSteps=plan?{...plan as object,steps:(await h.db.query("SELECT * FROM agent_plan_steps WHERE plan_version_id=$1 ORDER BY ordinal",[session.current_plan_version_id])).rows}:null; const guidanceUris=[`workmesh://workspace/${actor(request).workspaceId}/guidance`,`workmesh://team/${session.team_id}/guidance`,...(session.project_id?[`workmesh://project/${session.project_id}/guidance`]:[])]; return {session,workItem,plan:planWithSteps,contextSnapshotId:session.context_snapshot_id,guidanceUris}; });
  app.put("/api/v1/agent-sessions/:id/plan", async request => { const body = publishPlanInputSchema.parse(request.body); return commands.publishPlan(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agent-sessions/:id/signals", async request => { const body = signalAgentSessionInputSchema.parse(request.body); return commands.signal(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agent-sessions/:id/stop-ack", async request => { const body = stopAcknowledgementInputSchema.parse(request.body); return commands.stopAck(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agent-sessions/:id/complete", async request => { const body = completeAgentSessionInputSchema.parse(request.body); return commands.finishSession(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/agent-sessions/:id/fail", async request => { const body = failAgentSessionInputSchema.parse(request.body); return commands.finishSession(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body, true); });
  app.post("/api/v1/agent-sessions/:id/retry", async request => { const body = retryAgentSessionInputSchema.parse(request.body); return commands.retrySession(h.db,h.meta(request,body,{id:id(request)}),id(request),parseRevision(h.header(request,"if-match")),body); });
  app.post("/api/v1/artifacts", async request => { const body = artifactInputSchema.parse(request.body); return commands.publishArtifact(h.db, h.meta(request, body), body); });
  app.get("/api/v1/artifacts", async request => { const query = z.object({ sessionId: z.string().uuid().optional(), workItemId: z.string().uuid().optional() }).parse(request.query); const current=actor(request); const values: unknown[] = [current.workspaceId]; const where = ["workspace_id=$1"]; if(current.kind==="agent"){ await readableSession(request,h,current.agentSessionId!); values.push(current.agentSessionId!); where.push(`session_id=$${values.length}`); } else if(query.sessionId){ values.push(query.sessionId);where.push(`session_id=$${values.length}`); await readableSession(request,h,query.sessionId); } else if(current.workspaceRole!=="admin") { values.push(current.id); where.push(`EXISTS(SELECT 1 FROM agent_sessions s JOIN memberships m ON m.workspace_id=s.workspace_id AND m.team_id=s.team_id WHERE s.id=artifacts.session_id AND m.actor_id=$${values.length})`); } if (query.workItemId) { values.push(query.workItemId); where.push(`work_item_id=$${values.length}`); } return (await h.db.query(`SELECT * FROM artifacts WHERE ${where.join(" AND ")} ORDER BY created_at DESC`, values)).rows; });
  app.post("/api/v1/approvals", async request => { const body = requestApprovalInputSchema.parse(request.body); return commands.requestApproval(h.db, h.meta(request, body), body); });
  app.get("/api/v1/approvals", async request => { const query = z.object({ sessionId: z.string().uuid().optional(), status: z.string().optional() }).parse(request.query); const current=actor(request); const values: unknown[] = [current.workspaceId]; const where = ["workspace_id=$1"]; if(current.kind==="agent"){ await readableSession(request,h,current.agentSessionId!); values.push(current.agentSessionId!);where.push(`session_id=$${values.length}`); } else if(query.sessionId){ values.push(query.sessionId);where.push(`session_id=$${values.length}`);await readableSession(request,h,query.sessionId); } else if(current.workspaceRole!=="admin") { values.push(current.id); where.push(`EXISTS(SELECT 1 FROM agent_sessions s JOIN memberships m ON m.workspace_id=s.workspace_id AND m.team_id=s.team_id WHERE s.id=approvals.session_id AND m.actor_id=$${values.length})`); } if (query.status) { values.push(query.status); where.push(`status=$${values.length}`); } return (await h.db.query(`SELECT * FROM approvals WHERE ${where.join(" AND ")} ORDER BY created_at DESC`, values)).rows; });
  app.get("/api/v1/approvals/:id", async request => { const row = (await h.db.query<{session_id:string}>("SELECT session_id FROM approvals WHERE id=$1 AND workspace_id=$2", [id(request), actor(request).workspaceId])).rows[0]; if (!row) throw new DomainError("NOT_FOUND", "Approval not found"); await readableSession(request,h,row.session_id); return (await h.db.query("SELECT * FROM approvals WHERE id=$1",[id(request)])).rows[0]; });
  app.post("/api/v1/approvals/:id/decide", async request => { const body = decideApprovalInputSchema.parse(request.body); return commands.decideApproval(h.db, h.meta(request, body, { id: id(request) }), id(request), parseRevision(h.header(request, "if-match")), body); });
  app.post("/api/v1/approvals/:id/consume", async request => { const body=consumeApprovalInputSchema.parse(request.body); return commands.consumeApproval(h.db,h.meta(request,body,{id:id(request)}),id(request),parseRevision(h.header(request,"if-match")),body); });

  const guidance = async (request:FastifyRequest, scope:"workspace"|"team"|"project") => {
    const scopeId=id(request); const current=actor(request);
    if(scope==="workspace") { if(scopeId!==current.workspaceId) throw new DomainError("RESOURCE_SCOPE_DENIED","Workspace guidance is outside the actor scope"); if(current.kind==="agent") await readableSession(request,h,current.agentSessionId!); const row=(await h.db.query<{id:string;revision:number;updated_at:Date}>("SELECT id,revision,updated_at FROM workspaces WHERE id=$1",[scopeId])).rows[0]; if(!row) throw new DomainError("NOT_FOUND","Workspace not found"); return {scope,scopeId:row.id,revision:row.revision,markdown:"",updatedAt:row.updated_at}; }
    if(scope==="team") { if(current.kind==="agent") { const session=await readableSession(request,h,current.agentSessionId!); if(session.team_id!==scopeId) throw new DomainError("RESOURCE_SCOPE_DENIED","Agent token cannot read this team guidance"); } else await h.readableTeam(request,scopeId); const row=(await h.db.query<{id:string;revision:number;updated_at:Date}>("SELECT id,revision,updated_at FROM teams WHERE id=$1 AND workspace_id=$2 AND deleted_at IS NULL",[scopeId,current.workspaceId])).rows[0]; if(!row) throw new DomainError("NOT_FOUND","Team not found"); return {scope,scopeId:row.id,revision:row.revision,markdown:"",updatedAt:row.updated_at}; }
    const row=(await h.db.query<{id:string;team_id:string;revision:number;updated_at:Date;description:string|null}>("SELECT id,team_id,revision,updated_at,description FROM projects WHERE id=$1 AND workspace_id=$2 AND deleted_at IS NULL",[scopeId,current.workspaceId])).rows[0]; if(!row) throw new DomainError("NOT_FOUND","Project not found"); if(current.kind==="agent") { const session=await readableSession(request,h,current.agentSessionId!); const ownsProject=session.project_id===scopeId || Boolean(session.work_item_id && (await h.db.query("SELECT 1 FROM work_items WHERE id=$1 AND project_id=$2",[session.work_item_id,scopeId])).rowCount); if(session.team_id!==row.team_id || !ownsProject) throw new DomainError("RESOURCE_SCOPE_DENIED","Agent token cannot read this project guidance"); } else await h.readableTeam(request,row.team_id); return {scope,scopeId:row.id,revision:row.revision,markdown:row.description??"",updatedAt:row.updated_at};
  };
  app.get("/api/v1/workspaces/:id/guidance",async request=>guidance(request,"workspace"));
  app.get("/api/v1/teams/:id/guidance",async request=>guidance(request,"team"));
  app.get("/api/v1/projects/:id/guidance",async request=>guidance(request,"project"));
}
