import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js'
import { WorkMeshClient, WorkMeshSdkError } from '@workmesh/agent-sdk'
import { z } from 'zod'

export type McpMode = 'read-only' | 'read-write'
export interface WorkMeshMcpOptions { client: WorkMeshClient; mode?: McpMode }

const sessionId = z.string().uuid()
const idempotencyKey = z.string().min(1).max(255).optional()

export function createWorkMeshMcpServer(options: WorkMeshMcpOptions): McpServer {
  const server = new McpServer({ name: 'workmesh-mcp', version: '0.1.0' })
  server.registerResource('work-item', new ResourceTemplate('workmesh://work-item/{id}', { list: undefined }), { description: 'Current WorkMesh work item and its revision.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getWorkItem(String(variables.id))))
  server.registerResource('session-context', new ResourceTemplate('workmesh://session/{id}/context', { list: undefined }), { description: 'Bounded context manifest for an agent session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getSessionContext(String(variables.id))))
  server.registerResource('session-plan', new ResourceTemplate('workmesh://session/{id}/plan', { list: undefined }), { description: 'Current versioned session plan.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getPlan(String(variables.id))))
  server.registerResource('session-activity', new ResourceTemplate('workmesh://session/{id}/activity', { list: undefined }), { description: 'Immutable agent activities for a session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getActivities(String(variables.id))))
  server.registerResource('workspace-guidance', new ResourceTemplate('workmesh://workspace/{id}/guidance', { list: undefined }), { description: 'Workspace guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('workspace', String(variables.id))))
  server.registerResource('team-guidance', new ResourceTemplate('workmesh://team/{id}/guidance', { list: undefined }), { description: 'Team guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('team', String(variables.id))))
  server.registerResource('project-guidance', new ResourceTemplate('workmesh://project/{id}/guidance', { list: undefined }), { description: 'Project guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('project', String(variables.id))))

  server.registerTool('list_work_items', { description: 'List only work items authorized for this session.', inputSchema: { teamId: z.string().uuid().optional(), query: z.string().max(500).optional(), statusId: z.string().uuid().optional() } }, async input => tool(() => options.client.listWorkItems(input)))
  server.registerTool('get_work_item', { description: 'Get one authorized work item.', inputSchema: { workItemId: z.string().uuid() } }, async input => tool(() => options.client.getWorkItem(input.workItemId)))

  if (options.mode !== 'read-only') registerMutations(server, options.client)
  return server
}

function registerMutations(server: McpServer, client: WorkMeshClient): void {
  server.registerTool('ack_agent_session', { description: 'Acknowledge receipt of the current Agent session. This is an immutable session transition.', inputSchema: { sessionId, summary: z.string().min(1).max(2_000), externalUrls: z.array(z.object({ label: z.string().min(1), url: z.string().url() })).optional(), idempotencyKey } }, async input => tool(() => client.acknowledge(input.sessionId, { summary: input.summary, externalUrls: input.externalUrls }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('heartbeat', { description: 'Record diagnostic session liveness; it does not grant permission or change workflow state.', inputSchema: { sessionId, currentStepId: z.string().uuid().optional(), usage: z.object({ runtimeSeconds: z.number().int().nonnegative(), inputTokens: z.number().int().nonnegative().optional(), outputTokens: z.number().int().nonnegative().optional(), toolCalls: z.number().int().nonnegative().optional() }), idempotencyKey } }, async input => tool(() => client.heartbeat(input.sessionId, { currentStepId: input.currentStepId, usage: input.usage }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('append_activity', { description: 'Append an immutable, operational activity. Never include hidden chain-of-thought or secrets.', inputSchema: { sessionId, kind: z.string().min(1), summary: z.string().min(1).max(10_000), detailsMarkdown: z.string().max(50_000).optional(), toolInvocation: z.unknown().optional(), artifactIds: z.array(z.string().uuid()).optional(), references: z.array(z.unknown()).optional(), visibility: z.enum(['workspace', 'team', 'private']).optional(), ephemeral: z.boolean().optional(), idempotencyKey } }, async input => tool(() => client.appendActivity(input.sessionId, { kind: input.kind, summary: input.summary, detailsMarkdown: input.detailsMarkdown, toolInvocation: input.toolInvocation, artifactIds: input.artifactIds, references: input.references, visibility: input.visibility, ephemeral: input.ephemeral }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('publish_plan', { description: 'Publish a new immutable plan version. Requires the current plan revision; conflicts are returned without retry.', inputSchema: { sessionId, revision: z.number().int().positive(), changeSummary: z.string().min(1).max(5_000), approvalId: z.string().uuid().optional(), approvalPayloadHash: z.string().regex(/^sha256:[a-f0-9]{64}$/).optional(), steps: z.array(z.object({ id: z.string().uuid(), title: z.string().min(1), description: z.string().optional(), status: z.enum(['pending', 'in_progress', 'blocked', 'completed', 'canceled']).optional(), ordinal: z.number().int().nonnegative(), ownerActorId: z.string().uuid().optional(), dependsOn: z.array(z.string().uuid()).optional(), acceptanceCriteria: z.array(z.string()).optional(), expectedArtifacts: z.array(z.enum(['commit', 'pull_request', 'test_report', 'document', 'link', 'file', 'other'])).optional(), cancellationReason: z.string().optional() })).min(1), idempotencyKey } }, async input => tool(() => client.publishPlan(input.sessionId, { changeSummary: input.changeSummary, approvalId: input.approvalId, approvalPayloadHash: input.approvalPayloadHash, steps: input.steps.map(step => ({ ...step, status: step.status ?? 'pending', dependsOn: step.dependsOn ?? [], acceptanceCriteria: step.acceptanceCriteria ?? [], expectedArtifacts: step.expectedArtifacts ?? [] })) }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
  server.registerTool('send_message', { description: 'Append an auditable Agent message activity to the current session; it does not impersonate a human prompt.', inputSchema: { sessionId, bodyMarkdown: z.string().min(1).max(50_000), idempotencyKey } }, async input => tool(() => client.sendMessage(input.sessionId, input.bodyMarkdown, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('ask', { description: 'Append an auditable question activity for authorized humans; it does not impersonate a human prompt.', inputSchema: { sessionId, question: z.string().min(1).max(50_000), idempotencyKey } }, async input => tool(() => client.askQuestion(input.sessionId, input.question, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('request_approval', { description: 'Request an auditable human approval for a concrete action. Payload must be sanitized and hashed.', inputSchema: { sessionId, approvalType: z.string().min(1), actionName: z.string().min(1), actionPayloadSanitized: z.record(z.unknown()), actionPayloadHash: z.string().regex(/^sha256:[a-f0-9]{64}$/), riskLevel: z.enum(['low', 'medium', 'high', 'critical']), rationaleSummary: z.string().min(1), requiredApprovals: z.number().int().positive().optional(), expiresAt: z.string().datetime({ offset: true }), idempotencyKey } }, async input => tool(() => client.requestApproval({ sessionId: input.sessionId, approvalType: input.approvalType, actionName: input.actionName, actionPayloadSanitized: input.actionPayloadSanitized, actionPayloadHash: input.actionPayloadHash, riskLevel: input.riskLevel, rationaleSummary: input.rationaleSummary, requiredApprovals: input.requiredApprovals, expiresAt: input.expiresAt }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('publish_artifact', { description: 'Publish immutable, provenance-bearing artifact metadata for the current session.', inputSchema: { sessionId, workItemId: z.string().uuid().optional(), type: z.enum(['commit', 'pull_request', 'test_report', 'document', 'link', 'file', 'other']), title: z.string().min(1), uri: z.string().url().optional(), checksum: z.string().regex(/^sha256:[a-f0-9]{64}$/).optional(), sourceTool: z.string().optional(), metadata: z.record(z.unknown()).optional(), idempotencyKey } }, async input => tool(() => client.publishArtifact(input, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('complete_session', { description: 'Complete a session with evidence or an explicit no-artifact reason.', inputSchema: { sessionId, revision: z.number().int().positive(), summary: z.string().min(1), artifactIds: z.array(z.string().uuid()).optional(), checks: z.array(z.object({ name: z.string().min(1), command: z.string().optional(), status: z.enum(['passed', 'failed', 'skipped']), summary: z.string().min(1) })).optional(), limitations: z.array(z.string()).optional(), noArtifactReason: z.string().optional(), idempotencyKey } }, async input => tool(() => client.complete(input.sessionId, { summary: input.summary, artifactIds: input.artifactIds ?? [], checks: input.checks ?? [], limitations: input.limitations ?? [], noArtifactReason: input.noArtifactReason }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
  server.registerTool('fail_session', { description: 'Fail an active session with a concise operational explanation and evidence.', inputSchema: { sessionId, revision: z.number().int().positive(), code: z.string().min(1), summary: z.string().min(1), retryable: z.boolean().optional(), evidence: z.array(z.string()).optional(), idempotencyKey } }, async input => tool(() => client.fail(input.sessionId, { code: input.code, summary: input.summary, retryable: input.retryable, evidence: input.evidence }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
}

function resource(uri: URL, value: unknown) { return { contents: [{ uri: uri.toString(), mimeType: 'application/json', text: JSON.stringify(value) }] } }
async function tool(call: () => Promise<unknown>) {
  try {
    const data = await call()
    return { content: [{ type: 'text' as const, text: JSON.stringify(data) }], structuredContent: { data } }
  } catch (error) {
    const details = error instanceof WorkMeshSdkError ? { code: error.code, message: error.message, correlationId: error.correlationId, details: error.details } : { code: 'MCP_UPSTREAM_ERROR', message: error instanceof Error ? error.message : 'Unknown upstream error' }
    return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ error: details }) }], structuredContent: { error: details } }
  }
}
