import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js'
import { WorkMeshClient, WorkMeshSdkError } from '@workmesh/agent-sdk'
import { z } from 'zod'

export type McpMode = 'read-only' | 'read-write'
export interface WorkMeshMcpOptions { client: WorkMeshClient; mode?: McpMode }

const sessionId = z.string().uuid()
const idempotencyKey = z.string().min(1).max(255).optional()
const capability = z.enum(['work:read', 'work:write', 'comment:write', 'plan:write', 'message:write', 'artifact:write', 'repo:read', 'repo:write_branch', 'repo:open_pr', 'repo:merge', 'ci:run', 'deploy:staging', 'deploy:production', 'secrets:use', 'automation:manage', 'admin:*'])

export function createWorkMeshMcpServer(options: WorkMeshMcpOptions): McpServer {
  const server = new McpServer({ name: 'workmesh-mcp', version: '0.1.0' })
  server.registerResource('work-item', new ResourceTemplate('workmesh://work-item/{id}', { list: undefined }), { description: 'Current WorkMesh work item and its revision.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getWorkItem(String(variables.id))))
  server.registerResource('session-context', new ResourceTemplate('workmesh://session/{id}/context', { list: undefined }), { description: 'Bounded context manifest for an agent session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getSessionContext(String(variables.id))))
  server.registerResource('session-plan', new ResourceTemplate('workmesh://session/{id}/plan', { list: undefined }), { description: 'Current versioned session plan.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getPlan(String(variables.id))))
  server.registerResource('session-activity', new ResourceTemplate('workmesh://session/{id}/activity', { list: undefined }), { description: 'Immutable agent activities for a session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getActivities(String(variables.id))))
  server.registerResource('workspace-guidance', new ResourceTemplate('workmesh://workspace/{id}/guidance', { list: undefined }), { description: 'Workspace guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('workspace', String(variables.id))))
  server.registerResource('team-guidance', new ResourceTemplate('workmesh://team/{id}/guidance', { list: undefined }), { description: 'Team guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('team', String(variables.id))))
  server.registerResource('project-guidance', new ResourceTemplate('workmesh://project/{id}/guidance', { list: undefined }), { description: 'Project guidance available to the authenticated session.', mimeType: 'application/json' }, async (uri, variables) => resource(uri, await options.client.getGuidance('project', String(variables.id))))

  server.registerTool('list_work_items', { description: 'List only work items authorized for this session.', inputSchema: { teamId: z.string().uuid().optional(), query: z.string().max(500).optional(), statusId: z.string().uuid().optional() } }, async input => tool(() => options.client.listWorkItems(input)))
  server.registerTool('get_work_item', { description: 'Get one authorized work item.', inputSchema: { workItemId: z.string().uuid() } }, async input => tool(() => options.client.getWorkItem(input.workItemId)))

  server.registerTool('get_work_room', { description: 'Read the human-visible durable Work Room for one work item, project, or session.', inputSchema: { workItemId: z.string().uuid().optional(), projectId: z.string().uuid().optional(), sessionId: z.string().uuid().optional() } }, async input => tool(() => options.client.getRoom(input)))

  if (options.mode !== 'read-only') registerMutations(server, options.client)
  return server
}

function registerMutations(server: McpServer, client: WorkMeshClient): void {
  server.registerTool('post_work_room_message', { description: 'Post an auditable typed Work Room message to authorized recipients. Do not use it for hidden agent-private communication.', inputSchema: { roomId: z.string().uuid(), intent: z.enum(['inform','ask','answer','propose','decide','claim','handoff','blocker','review_request','review_result','status']), body: z.string().min(1).max(50_000), recipientActorId: z.string().uuid().optional(), recipientActorIds: z.array(z.string().uuid()).min(1).max(50).optional(), replyToMessageId: z.string().uuid().optional(), threadId: z.string().uuid().optional(), payload: z.record(z.unknown()).optional(), sessionId: z.string().uuid(), requiresResponse: z.boolean().optional(), idempotencyKey } }, async input => tool(() => client.postRoomMessage(input.roomId, { intent: input.intent, body: input.body, recipientActorId: input.recipientActorId, recipientActorIds: input.recipientActorIds, replyToMessageId: input.replyToMessageId, threadId: input.threadId, payload: input.payload, sessionId: input.sessionId, requiresResponse: input.requiresResponse }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('comment_plan_step', { description: 'Append an immutable, session-scoped comment to a stable plan step in its plan version.', inputSchema: { sessionId, planVersionId: z.string().uuid(), planStepId: z.string().uuid(), body: z.string().min(1).max(50_000), references: z.array(z.unknown()).max(100).optional(), idempotencyKey } }, async input => tool(() => client.commentPlanStep(input.sessionId, { planVersionId: input.planVersionId, planStepId: input.planStepId, body: input.body, references: input.references }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('propose_plan_step_assignment', { description: 'Propose an exact agent or skill assignment for a plan step; this creates an auditable proposal, not an unapproved reassignment.', inputSchema: { sessionId, planStepId: z.string().uuid(), agentId: z.string().uuid().optional(), skill: z.string().min(1).max(160).optional(), rationale: z.string().min(1).max(10_000), idempotencyKey } }, async input => tool(() => client.proposeAssignment(input.sessionId, { planStepId: input.planStepId, agentId: input.agentId, skill: input.skill, rationale: input.rationale }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('create_child_session', { description: 'Create a bounded child agent session for one stable plan step. Parent budget, delegation, team access, and concurrency are enforced by the server.', inputSchema: { parentSessionId: sessionId, agentId: z.string().uuid(), planStepId: z.string().uuid(), planVersionId: z.string().uuid(), role: z.enum(['executor','reviewer','researcher']).optional(), initialPrompt: z.string().min(1).max(50_000), required: z.boolean().optional(), budget: z.record(z.number()).optional(), idempotencyKey } }, async input => tool(() => client.createChildSession(input.parentSessionId, { agentId: input.agentId, planStepId: input.planStepId, planVersionId: input.planVersionId, role: input.role, initialPrompt: input.initialPrompt, required: input.required, budget: input.budget }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('append_context_delta', { description: 'Append an immutable, scoped context delta and make its derived snapshot current for this session.', inputSchema: { sessionId, baseSnapshotId: z.string().uuid(), additions: z.array(z.union([
    z.object({ sourceType: z.enum(['artifact','message','work_item','plan_step']), sourceId: z.string().uuid(), hash: z.string().regex(/^sha256:[a-f0-9]{64}$/) }).strict(),
    z.object({ sourceType: z.literal('guidance'), uri: z.string().url(), hash: z.string().regex(/^sha256:[a-f0-9]{64}$/) }).strict(),
  ])).min(1).max(100), rationale: z.string().min(1).max(10_000), idempotencyKey } }, async input => tool(() => client.appendContextDelta(input.sessionId, { baseSnapshotId: input.baseSnapshotId, additions: input.additions, rationale: input.rationale }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('create_review_delegation', { description: 'Create a scoped reviewer child session and review-shared plan-step lease. The server grants only read and code-review artifact capabilities.', inputSchema: { sessionId, reviewerAgentId: z.string().uuid(), planStepId: z.string().uuid(), planVersionId: z.string().uuid(), initialPrompt: z.string().min(1).max(50_000), ttlSeconds: z.number().int().min(10).max(3_600).optional(), idempotencyKey } }, async input => tool(() => client.createReviewDelegation(input.sessionId, { reviewerAgentId: input.reviewerAgentId, planStepId: input.planStepId, planVersionId: input.planVersionId, initialPrompt: input.initialPrompt, ttlSeconds: input.ttlSeconds }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('acquire_lease', { description: 'Acquire a coordination lease after normal session authorization; it never grants permissions.', inputSchema: { sessionId, resourceType: z.enum(['work_item','plan_step']), resourceId: z.string().uuid(), kind: z.enum(['exclusive','review_shared']).optional(), ttlSeconds: z.number().int().positive().optional(), reason: z.string().min(1), idempotencyKey } }, async input => tool(() => client.acquireLease(input, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('offer_handoff', { description: 'Offer a scoped, auditable handoff from the current agent session. Acceptance remains a human control-plane action.', inputSchema: { fromSessionId: sessionId, targetAgentId: z.string().uuid().optional(), targetSkill: z.string().min(1).max(160).optional(), scopeType: z.enum(['workspace','project','work_item','plan_step']).optional(), scopeId: z.string().uuid().optional(), summary: z.string().min(1).max(20_000), completedWork: z.array(z.string().min(1).max(10_000)).max(100).optional(), remainingWork: z.array(z.string().min(1).max(10_000)).max(100).optional(), openQuestions: z.array(z.string().min(1).max(2_000)).max(100).optional(), risks: z.array(z.string().min(1).max(2_000)).max(100).optional(), acceptanceCriteria: z.array(z.string().min(1).max(2_000)).max(100).optional(), requestedAction: z.string().min(1).max(10_000).optional(), leaseTransferPolicy: z.enum(['retain','transfer','release']).optional(), artifactIds: z.array(z.string().uuid()).max(100).optional(), contextSnapshotId: z.string().uuid().optional(), requestedCapabilities: z.array(capability).max(50).optional(), status: z.enum(['draft','requested']).optional(), idempotencyKey } }, async input => tool(() => client.offerHandoff({ fromSessionId: input.fromSessionId, targetAgentId: input.targetAgentId, targetSkill: input.targetSkill, scopeType: input.scopeType, scopeId: input.scopeId, summary: input.summary, completedWork: input.completedWork, remainingWork: input.remainingWork, openQuestions: input.openQuestions, risks: input.risks, acceptanceCriteria: input.acceptanceCriteria, requestedAction: input.requestedAction, leaseTransferPolicy: input.leaseTransferPolicy, artifactIds: input.artifactIds, contextSnapshotId: input.contextSnapshotId, requestedCapabilities: input.requestedCapabilities, status: input.status }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('inspect_pending_handoff', { description: 'Inspect the full structured package and immutable context snapshot for an exact-target requested handoff using the configured installation identity. This is read-only and grants no work authority.', inputSchema: { handoffId: z.string().uuid() } }, async input => tool(() => client.inspectPendingHandoff(input.handoffId)))
  server.registerTool('request_handoff', { description: 'Request a previously drafted handoff after server-side source-session authorization.', inputSchema: { handoffId: z.string().uuid(), reason: z.string().min(1).max(10_000).optional(), idempotencyKey } }, async input => tool(() => client.requestHandoff(input.handoffId, { reason: input.reason }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('reject_handoff', { description: 'Reject an exact-target handoff using a protocol machine reason.', inputSchema: { handoffId: z.string().uuid(), machineReason: z.enum(['capability_missing', 'budget_insufficient', 'concurrency_limit', 'context_incomplete', 'conflict', 'manual_reject']), idempotencyKey } }, async input => tool(() => client.rejectHandoff(input.handoffId, { machineReason: input.machineReason }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('ack_agent_session', { description: 'Acknowledge receipt of the current Agent session. This is an immutable session transition.', inputSchema: { sessionId, summary: z.string().min(1).max(2_000), externalUrls: z.array(z.object({ label: z.string().min(1), url: z.string().url() })).optional(), idempotencyKey } }, async input => tool(() => client.acknowledge(input.sessionId, { summary: input.summary, externalUrls: input.externalUrls }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('heartbeat', { description: 'Record diagnostic session liveness; it does not grant permission or change workflow state.', inputSchema: { sessionId, currentStepId: z.string().uuid().optional(), usage: z.object({ runtimeSeconds: z.number().int().nonnegative(), inputTokens: z.number().int().nonnegative().optional(), outputTokens: z.number().int().nonnegative().optional(), toolCalls: z.number().int().nonnegative().optional() }), idempotencyKey } }, async input => tool(() => client.heartbeat(input.sessionId, { currentStepId: input.currentStepId, usage: input.usage }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('append_activity', { description: 'Append an immutable, operational activity. Never include hidden chain-of-thought or secrets.', inputSchema: { sessionId, kind: z.string().min(1), summary: z.string().min(1).max(10_000), detailsMarkdown: z.string().max(50_000).optional(), toolInvocation: z.unknown().optional(), artifactIds: z.array(z.string().uuid()).optional(), references: z.array(z.unknown()).optional(), visibility: z.enum(['workspace', 'team', 'private']).optional(), ephemeral: z.boolean().optional(), idempotencyKey } }, async input => tool(() => client.appendActivity(input.sessionId, { kind: input.kind, summary: input.summary, detailsMarkdown: input.detailsMarkdown, toolInvocation: input.toolInvocation, artifactIds: input.artifactIds, references: input.references, visibility: input.visibility, ephemeral: input.ephemeral }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('publish_plan', { description: 'Publish a new immutable plan version. Requires the current plan revision; conflicts are returned without retry.', inputSchema: { sessionId, revision: z.number().int().positive(), changeSummary: z.string().min(1).max(5_000), approvalId: z.string().uuid().optional(), approvalPayloadHash: z.string().regex(/^sha256:[a-f0-9]{64}$/).optional(), steps: z.array(z.object({ id: z.string().uuid(), title: z.string().min(1), description: z.string().optional(), status: z.enum(['pending', 'in_progress', 'blocked', 'completed', 'canceled']).optional(), ordinal: z.number().int().nonnegative(), ownerActorId: z.string().uuid().optional(), dependsOn: z.array(z.string().uuid()).optional(), acceptanceCriteria: z.array(z.string()).optional(), expectedArtifacts: z.array(z.enum(['commit', 'pull_request', 'test_report', 'document', 'link', 'file', 'other'])).optional(), cancellationReason: z.string().optional() })).min(1), idempotencyKey } }, async input => tool(() => client.publishPlan(input.sessionId, { changeSummary: input.changeSummary, approvalId: input.approvalId, approvalPayloadHash: input.approvalPayloadHash, steps: input.steps.map(step => ({ ...step, status: step.status ?? 'pending', dependsOn: step.dependsOn ?? [], acceptanceCriteria: step.acceptanceCriteria ?? [], expectedArtifacts: step.expectedArtifacts ?? [] })) }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
  server.registerTool('send_message', { description: 'Append an auditable Agent message activity to the current session; it does not impersonate a human prompt.', inputSchema: { sessionId, bodyMarkdown: z.string().min(1).max(50_000), idempotencyKey } }, async input => tool(() => client.sendMessage(input.sessionId, input.bodyMarkdown, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('ask', { description: 'Append an auditable question activity for authorized humans; it does not impersonate a human prompt.', inputSchema: { sessionId, question: z.string().min(1).max(50_000), idempotencyKey } }, async input => tool(() => client.askQuestion(input.sessionId, input.question, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('request_approval', { description: 'Request an auditable human approval for a concrete action. Payload must be sanitized and hashed.', inputSchema: { sessionId, approvalType: z.string().min(1), actionName: z.string().min(1), actionPayloadSanitized: z.record(z.unknown()), actionPayloadHash: z.string().regex(/^sha256:[a-f0-9]{64}$/), riskLevel: z.enum(['low', 'medium', 'high', 'critical']), rationaleSummary: z.string().min(1), requiredApprovals: z.number().int().positive().optional(), expiresAt: z.string().datetime({ offset: true }), idempotencyKey } }, async input => tool(() => client.requestApproval({ sessionId: input.sessionId, approvalType: input.approvalType, actionName: input.actionName, actionPayloadSanitized: input.actionPayloadSanitized, actionPayloadHash: input.actionPayloadHash, riskLevel: input.riskLevel, rationaleSummary: input.rationaleSummary, requiredApprovals: input.requiredApprovals, expiresAt: input.expiresAt }, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('publish_artifact', { description: 'Publish immutable, provenance-bearing artifact metadata for the current session.', inputSchema: { sessionId, workItemId: z.string().uuid().optional(), type: z.enum(['commit', 'pull_request', 'test_report', 'code_review', 'document', 'link', 'file', 'other']), title: z.string().min(1), uri: z.string().url().optional(), checksum: z.string().regex(/^sha256:[a-f0-9]{64}$/).optional(), sourceTool: z.string().optional(), metadata: z.record(z.unknown()).optional(), idempotencyKey } }, async input => tool(() => client.publishArtifact(input, { idempotencyKey: input.idempotencyKey })))
  server.registerTool('complete_session', { description: 'Complete a session with evidence or an explicit no-artifact reason.', inputSchema: { sessionId, revision: z.number().int().positive(), summary: z.string().min(1), artifactIds: z.array(z.string().uuid()).optional(), checks: z.array(z.object({ name: z.string().min(1), command: z.string().optional(), status: z.enum(['passed', 'failed', 'skipped']), summary: z.string().min(1) })).optional(), limitations: z.array(z.string()).optional(), noArtifactReason: z.string().optional(), idempotencyKey } }, async input => tool(() => client.complete(input.sessionId, { summary: input.summary, artifactIds: input.artifactIds ?? [], checks: input.checks ?? [], limitations: input.limitations ?? [], noArtifactReason: input.noArtifactReason }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
  server.registerTool('fail_session', { description: 'Fail an active session with a concise operational explanation and evidence.', inputSchema: { sessionId, revision: z.number().int().positive(), code: z.string().min(1), summary: z.string().min(1), retryable: z.boolean().optional(), evidence: z.array(z.string()).optional(), idempotencyKey } }, async input => tool(() => client.fail(input.sessionId, { code: input.code, summary: input.summary, retryable: input.retryable, evidence: input.evidence }, { idempotencyKey: input.idempotencyKey, ifMatch: input.revision })))
}

function resource(uri: URL, value: unknown) { return { contents: [{ uri: uri.toString(), mimeType: 'application/json', text: JSON.stringify(value) }] } }
async function tool(call: () => Promise<unknown>) {
  try {
    const data = await call()
    return { content: [{ type: 'text' as const, text: JSON.stringify(data) }], structuredContent: { data } }
  } catch (error) {
    const details = error instanceof WorkMeshSdkError ? { code: error.code, message: error.message, correlationId: error.correlationId, details: error.details } : { code: 'MCP_UPSTREAM_ERROR', message: error instanceof Error ? error.message : 'Unknown upstream error' }
    return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify({ error: details }) }], structuredContent: { error: details } }
  }
}
