import { createHash } from 'node:crypto'
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { join, parse } from 'node:path'

const migrationsDirectory = join(import.meta.dirname, '../migrations')
const v1Directory = join(migrationsDirectory, 'v1')
const upgradesDirectory = join(migrationsDirectory, 'upgrades')
const baselineFile = '0001_v1_baseline.sql'
const manifestPath = join(import.meta.dirname, '../src/migration-manifest.ts')
const legacyFilePattern = /^(\d{4})_.*\.sql$/
const v1FilePattern = /^\d{4}_.*\.sql$/
const transactionControlPattern = /^\s*(?:BEGIN|COMMIT|ROLLBACK|START\s+TRANSACTION)\s*;\s*$/i

const canonicalize = (source: string): string => source.replace(/\r\n?/g, '\n')
const checksum = (source: string): string => createHash('sha256').update(canonicalize(source)).digest('hex')
const stripTransactionControl = (source: string): string => source
  .split('\n')
  .filter(line => !transactionControlPattern.test(line))
  .join('\n')
  .trim()

const forFreshBaseline = (file: string, source: string): string => {
  const withoutTransactions = stripTransactionControl(source)
  if (file === '0005_stage1_tokens_webhooks_events.sql') {
    return withoutTransactions.replace(
      "CREATE TYPE inbox_item_kind AS ENUM ('waiting_input','approval','session_stale');",
      "CREATE TYPE inbox_item_kind AS ENUM ('waiting_input','approval','session_stale','ask','review_request','blocker','handoff','mention');",
    )
  }
  if (file === '0007_stage2_work_rooms_leases_handoffs.sql') {
    return withoutTransactions.split('\n').filter(line => !/^ALTER TYPE inbox_item_kind ADD VALUE /i.test(line)).join('\n')
  }
  if (file === '0008_stage3_delivery_control_plane.sql') {
    return withoutTransactions.replace(
      "CREATE TYPE provider_kind AS ENUM ('fake','github');",
      "CREATE TYPE provider_kind AS ENUM ('fake','github','gitea');",
    )
  }
  if (file === '0019_stage4_gitea.sql') {
    return withoutTransactions.split('\n').filter(line => !/^ALTER TYPE provider_kind ADD VALUE /i.test(line)).join('\n')
  }
  if (file === '0032_agent_inbox_receipts.sql') {
    return withoutTransactions.split('\n').filter(line => !/^ALTER TYPE inbox_item_kind ADD VALUE /i.test(line)).join('\n')
  }
  return withoutTransactions
}

const forAtomicUpgrade = (file: string, source: string): string => {
  const withoutTransactions = stripTransactionControl(source)
  if (file !== '0019_stage4_gitea.sql') return withoutTransactions
  return withoutTransactions.replace(
    "ALTER TYPE provider_kind ADD VALUE IF NOT EXISTS 'gitea';",
    [
      'ALTER TABLE provider_connections DROP CONSTRAINT IF EXISTS provider_connections_check;',
      'ALTER TABLE provider_connections DROP CONSTRAINT IF EXISTS provider_connections_github_credentials_check;',
      'ALTER TABLE provider_connections ALTER COLUMN provider TYPE text USING provider::text;',
      'DROP TYPE provider_kind;',
      "CREATE TYPE provider_kind AS ENUM ('fake','github','gitea');",
      'ALTER TABLE provider_connections ALTER COLUMN provider TYPE provider_kind USING provider::provider_kind;',
      "ALTER TABLE provider_connections ADD CONSTRAINT provider_connections_check CHECK(provider<>'github' OR credentials_ciphertext IS NOT NULL);",
      "ALTER TABLE provider_connections ADD CONSTRAINT provider_connections_github_credentials_check CHECK(provider<>'github' OR credentials_ciphertext IS NOT NULL);",
    ].join('\n'),
  )
}

const legacyFiles = (await readdir(migrationsDirectory))
  .filter(file => legacyFilePattern.test(file))
  .sort((left, right) => left.localeCompare(right))

if (legacyFiles.length === 0) throw new Error('No legacy migrations found')

const legacyEntries: Array<Readonly<{ version: string; file: string; checksumSha256: string }>> = []
const legacySources = new Map<string, string>()
const baselineSections: string[] = [
  '-- Generated by packages/db/scripts/generate-v1-baseline.mts.',
  '-- Do not edit this file directly. Pre-v1 migrations remain the immutable source inventory.',
  '-- Transaction control belongs to the WorkMesh migration runner.',
  '',
]

for (const file of legacyFiles) {
  const source = canonicalize(await readFile(join(migrationsDirectory, file), 'utf8'))
  const version = parse(file).name
  legacyEntries.push({ version, file, checksumSha256: checksum(source) })
  legacySources.set(file, source)

  const body = forFreshBaseline(file, source)

  if (body.split('\n').some(line => transactionControlPattern.test(line))) {
    throw new Error(`Legacy migration ${file} still contains top-level transaction control`)
  }

  baselineSections.push(`-- legacy:${version}:begin`, body, `-- legacy:${version}:end`, '')
}

const baselineSource = `${baselineSections.join('\n').trim()}\n`
await mkdir(v1Directory, { recursive: true })
await writeFile(join(v1Directory, baselineFile), baselineSource, 'utf8')

const v1Entries = [] as Array<Readonly<{
  version: string
  file: string
  checksumSha256: string
}>>
for (const file of (await readdir(v1Directory))
  .filter(candidate => v1FilePattern.test(candidate))
  .sort((left, right) => left.localeCompare(right))) {
  const source = canonicalize(await readFile(join(v1Directory, file), 'utf8'))
  const version = parse(file).name
  if (source.split('\n').some(line => transactionControlPattern.test(line))) {
    throw new Error(`v1 migration ${file} contains top-level transaction control`)
  }
  v1Entries.push({ version, file: `v1/${file}`, checksumSha256: checksum(source) })
}
if (v1Entries[0]?.version !== '0001_v1_baseline') {
  throw new Error('The v1 manifest must begin with 0001_v1_baseline')
}

const supportedUpgradeEndpoints = [
  '0002_stage0_integrity_delivery',
  '0006_stage1_review_fixes',
  '0007_stage2_work_rooms_leases_handoffs',
  '0014_provider_action_kinds',
  '0021_stage4_a2a_direction_and_prompt_identity',
] as const
const bundleEntries: Array<Readonly<{ fromVersion: string; file: string; checksumSha256: string }>> = []
await mkdir(upgradesDirectory, { recursive: true })
for (const fromVersion of supportedUpgradeEndpoints) {
  const endpointIndex = legacyEntries.findIndex(entry => entry.version === fromVersion)
  if (endpointIndex < 0) throw new Error(`Unknown supported upgrade endpoint ${fromVersion}`)
  const bundleFile = `from_${fromVersion.slice(0, 4)}_to_v1.sql`
  const sections = [
    '-- Generated by packages/db/scripts/generate-v1-baseline.mts.',
    `-- Atomic pre-v1 upgrade bundle from ${fromVersion}.`,
    '-- Transaction control belongs to the WorkMesh migration runner.',
    '',
  ]
  for (const entry of legacyEntries.slice(endpointIndex + 1)) {
    const source = legacySources.get(entry.file)
    if (source === undefined) throw new Error(`Missing legacy source ${entry.file}`)
    sections.push(
      `-- legacy:${entry.version}:begin`,
      forAtomicUpgrade(entry.file, source),
      `-- legacy:${entry.version}:end`,
      '',
    )
  }
  const bundleSource = `${sections.join('\n').trim()}\n`
  await writeFile(join(upgradesDirectory, bundleFile), bundleSource, 'utf8')
  bundleEntries.push({ fromVersion, file: `upgrades/${bundleFile}`, checksumSha256: checksum(bundleSource) })
}

const manifestSource = `// Generated by packages/db/scripts/generate-v1-baseline.mts. Do not edit manually.\n\nexport type MigrationManifestEntry = Readonly<{\n  version: string\n  file: string\n  checksumSha256: string\n}>\n\nexport const legacyMigrationManifest = [\n${legacyEntries.map(entry => `  { version: '${entry.version}', file: '${entry.file}', checksumSha256: '${entry.checksumSha256}' },`).join('\n')}\n] as const satisfies readonly MigrationManifestEntry[]\n\nexport const v1MigrationManifest = [\n${v1Entries.map(entry => `  { version: '${entry.version}', file: '${entry.file}', checksumSha256: '${entry.checksumSha256}' },`).join('\n')}\n] as const satisfies readonly MigrationManifestEntry[]\n\nexport const legacyUpgradeBundleManifest = [\n${bundleEntries.map(entry => `  { fromVersion: '${entry.fromVersion}', file: '${entry.file}', checksumSha256: '${entry.checksumSha256}' },`).join('\n')}\n] as const\n\nexport const supportedLegacyUpgradeEndpoints = [\n${supportedUpgradeEndpoints.map(version => `  '${version}',`).join('\n')}\n] as const\n`

await writeFile(manifestPath, manifestSource, 'utf8')
console.log(`Generated ${baselineFile} from ${legacyEntries.length} immutable legacy migrations.`)
