import { type ApprovalViewerActionability, type HumanAttentionItem, type HumanAttentionKind, type HumanAttentionStatus } from '@workmesh/contracts';
export type HumanAttentionRow = Readonly<{
    source_type: 'decision' | 'approval' | 'inbox_item' | 'agent_session' | 'completion_suggestion';
    source_id: string;
    source_status: string;
    source_revision: number;
    kind: HumanAttentionKind;
    status: HumanAttentionStatus;
    workspace_id: string;
    team_id: string | null;
    project_id: string | null;
    work_item_id: string | null;
    session_id: string | null;
    target_revision: number | null;
    title: string;
    summary: string;
    impact_summary: string;
    risk_level: 'info' | 'low' | 'medium' | 'high' | 'critical';
    expires_at: Date | string | null;
    requested_by_actor_id: string;
    requested_by_kind: 'human' | 'agent' | 'service';
    requested_by_name: string;
    responsible_human_actor_id: string | null;
    responsible_human_name: string | null;
    payload: unknown;
    correlation_id: string | null;
    created_at: Date | string;
    updated_at: Date | string;
    updated_cursor?: string;
    recipient_actor_id: string | null;
}>;
export type HumanAttentionViewer = Readonly<{
    id: string;
    kind: 'human' | 'agent';
    workspaceRole: 'admin' | 'member';
}>;
export declare function projectHumanAttentionRow(row: HumanAttentionRow, observedAt?: Date, viewer?: HumanAttentionViewer, approvalActionability?: ApprovalViewerActionability): HumanAttentionItem;
export { humanAttentionProjectionSql } from '@workmesh/db';
